UserOfficeProject/user-office-core

- apps/user-office-frontend-e2e/cypress/integration/generic_templates.ts
- apps/user-office-frontend/src/components/questionary/questionaryComponents/GenericTemplate/GenericTemplateContainer.tsx
- apps/user-office-frontend/src/components/questionary/questionaryComponents/GenericTemplateBasis/QuestionaryComponentGenericTemplateBasis.tsx
Make the publication title field multiline to accommodate for longer titles.
Titles that contain more than 30 characters are truncated, so that it fits within the dialogue box.
- The field accepts 500 characters, so increasing the character limit was not necessary. Longer titles can fit into the text field by being typed on multiple lines.
- Additionally, Titles that are very long do not fit inside of the dialogue box properly.
- Some tests needed to be fixed as changes made to ensure titles could be typed on multiple lines broke some tests.
- Ensured that the user can type on multiple lines through manual testing.
- Added check to test to ensure that long titles are truncated after entry.
Part of UserOfficeProject/user-office-project-issue-tracker#239
> refactor: make titles multiline, truncate long titles & fix tests

- .github/workflows/test-build.yml
- apps/user-office-backend/src/config/stfc/configureSTFCEnvironment.ts
- apps/user-office-frontend/src/components/user/ExternalAuth.tsx
This will fix current login problem in develop and add external logout url for STFC
The current develop branch don't login when using an external token and also the external logout url must be set for users to be able to successfully logout
Manual testing
.github/workflows/test-build.yml
apps/user-office-backend/src/config/stfc/configureSTFCEnvironment.ts
apps/user-office-frontend/src/components/user/ExternalAuth.tsx
https://github.com/isisbusapps/docker-orchestration/pull/315
>  add external logout and fix login with token

- apps/user-office-backend/src/asyncJobs/jobs/checkAllCallsEnded.ts
- apps/user-office-backend/src/datasources/postgres/CallDataSource.ts
- apps/user-office-backend/src/resolvers/queries/CallsQuery.ts
- apps/user-office-frontend/src/generated/sdk.ts
Closes: [#714](https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/714)
We added a new filter to replace one that had been modified in another PR. This now correctly updates the call_ended field in postgres.
> Added a new filter to trigger call ended event

- apps/user-office-frontend/src/context/UserContextProvider.tsx
When a user logout in stfc the system will still make calls to the backend creating invalid token logs.This is shown by the below screenshot.
To get ready of unnecessary log failures. 
Manually tested on local dev
Fix the following errors from being created.
The following file was updated.
apps/user-office-frontend/src/context/UserContextProvider.tsx
> Update the logout function calling older in user context

- .github/workflows/build-push.yml
The `branch` param has been replaced with `environment`, as it better describes the purpose.
> fix: add ENVIRONMENT param

- apps/user-office-backend/src/eventHandlers/email/stfcEmailHandler.ts
Principal Investigator receiving email with wrong details when submitting to ISIS Rapid because call not picking the right proposal submission email template.
Currently users submitting proposals to Rapid call are receiving email created from incorrect template.
Manual tested
Closes: https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/732
File updated: apps/user-office-backend/src/eventHandlers/email/stfcEmailHandler.ts
- [`x] I have added tests to cover my changes.
> Hotfix: Update how stfc  email handler assign email templates

- apps/user-office-frontend-e2e/cypress/integration/settings.ts
- apps/user-office-frontend/src/components/common/SuperMaterialTable.tsx
- apps/user-office-frontend/src/hooks/call/useCallTemplates.ts
The close button on the create/update modal of SuperMaterialTable should also clean up the state of editing object. This wasn't the case and there was a bug after you try to edit some item, close the modal (using close button) and open the create item modal which shows the previously edited item instead of a clean creation state.
In every place we used the SuperMaterialTable this problem with showing the last edited item was present.
- manual tests
- e2e tests
https://jira.esss.lu.se/browse/SWAP-2879
https://user-images.githubusercontent.com/6333063/199449929-d0f4fc56-5055-4825-9e72-9b64296d7419.mp4
> fix: Fixing the state cleanup after modal close and cleaning some console warnings

- .github/workflows/build-push.yml
Trigger Jenkins only on develop
We don't want Jenkins to be triggered from any other branch than develop
> fix: trigger Jenkins only on develop

- .github/workflows/build-push.yml
- .github/workflows/test-build.yml
This PR is just fixing the deprecated set-output warnings in the github actions. https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> fix: Fix deprecated set-output warning in the actions

- apps/user-office-backend/docker-compose.yml
- apps/user-office-backend/index.ts
- apps/user-office-backend/package-lock.json
- apps/user-office-backend/package.json
- apps/user-office-backend/src/middlewares/factory.ts
- apps/user-office-frontend-e2e/cypress/integration/generalSeps.ts
- apps/user-office-frontend-e2e/cypress/integration/generic_templates.ts
- apps/user-office-frontend-e2e/cypress/integration/proposal_administration.ts
- apps/user-office-frontend-e2e/cypress/integration/samples.ts
- apps/user-office-frontend-e2e/cypress/integration/settings.ts
- apps/user-office-frontend/package-lock.json
- apps/user-office-frontend/package.json
- apps/user-office-frontend/src/context/DownloadContextProvider.tsx
- apps/user-office-frontend/src/context/UserContextProvider.tsx
In order to use only one way of sending authorization headers I try to remove the use of cookies and parsing them in the backend.
We were sending authorization headers with the jwt token and also including it in the cookies.
- manual tests
- e2e tests
It is mostly removing the cookies handling on the frontend and backend.
> refactor: Cleanup the react-cookie and cookie-parser. Use only express-jwt in all the requests.

- apps/user-office-backend/src/auth/ProposalAuthorization.ts
- apps/user-office-backend/src/datasources/postgres/CallDataSource.ts
- apps/user-office-frontend-e2e/cypress/integration/calls.ts
- apps/user-office-frontend/src/components/call/CallGeneralInfo.tsx
- apps/user-office-frontend/src/components/call/CreateUpdateCall.tsx
When the user officer update call end date and click next button, the stepper is not moving to the next page.
During a call user officer wants to be able to update call dates.
- manual tests
- e2e tests
https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/729
https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/730
Files changed:
- apps/user-office-frontend/src/components/call/CallGeneralInfo.tsx
- apps/user-office-backend/src/auth/ProposalAuthorization.ts
- apps/user-office-backend/src/datasources/postgres/CallDataSource.ts
- apps/user-office-frontend/src/components/call/CreateUpdateCall.tsx
- apps/user-office-frontend-e2e/cypress/integration/calls.ts
> fix: next button not working when updating call

- apps/user-office-frontend-e2e/cypress/integration/calls.ts
`Call display correct time test` is failing and needs to be updated because of a new feature which was added to calls.
This is part of https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/711
Files changed:
apps/user-office-frontend-e2e/cypress/integration/calls.ts
> Fix call displays correct time remaining test which are failing

- apps/user-office-frontend/src/components/template/TemplateTopicEditor.tsx
The template topic text length is fixed, UI should also has fixed text input length.
Bug fix
manual test
text input length constraint
`apps/user-office-frontend/src/components/template/TemplateTopicEditor.tsx` - Field component included inputProps
> fix: Add limit to template topic title length

- apps/user-office-frontend/src/components/proposal/ProposalTableOfficer.tsx
Currently, the proposal table contains the column Average Score.  
This field is used only internally and should not be seen on the table.
manual tests
apps/user-office-frontend/src/components/proposal/ProposalTableOfficer.tsx
> fix: hide average score

- apps/user-office-frontend/src/components/proposal/ParticipantModal.tsx
Close button is blocked by input field.
Close button should not be blocked in any circumstances.
* e2e test
*  manual test
apps/user-office-frontend/src/components/proposal/ParticipantModal.tsx
> fix: close icon is blocked by input field

- apps/user-office-frontend/src/components/questionary/questionaryComponents/NumberInput/QuestionNumberInputForm.tsx
When specifying unit it would be nice to have a quick link so that you can quickly navigate to units page
* manual testing
apps/user-office-frontend/src/components/questionary/questionaryComponents/NumberInput/QuestionNumberInputForm.tsx
> Added navigation link

- apps/user-office-frontend/src/components/common/StyledModal.tsx
- apps/user-office-frontend/src/components/questionary/questionaryComponents/NumberInput/QuestionNumberInputForm.tsx
- apps/user-office-frontend/src/components/template/QuestionEditor.tsx
- apps/user-office-frontend/src/components/template/QuestionTemplateRelationEditor.tsx
Question template modals are missing close button in the top right corner
* manual test
apps/user-office-frontend/src/components/template/QuestionEditor.tsx
apps/user-office-frontend/src/components/template/QuestionTemplateRelationEditor.tsx
> Fix: Some modals missing close modal button

- .github/workflows/build-push.yml
- apps/user-office-frontend-e2e/cypress/integration/generic_templates.ts
- apps/user-office-frontend-e2e/cypress/integration/proposals.ts
- apps/user-office-frontend-e2e/cypress/integration/samples.ts
- apps/user-office-frontend-e2e/cypress/integration/templates_advanced.ts
- apps/user-office-frontend-e2e/cypress/integration/templates_basic.ts
- apps/user-office-frontend/src/components/menu/MenuItems.tsx
Closes: UserOfficeProject/user-office-project-issue-tracker#726
Currently, when there is only one call open the user is taken straight to the proposal creation page when selecting `New Proposal`. This PR makes selecting the `New Proposal` menu option always take the user to the call selection page even when there is only one call.
With this PR when creating a proposal and there is only one call, selecting `New Proposal` will take the user to the call selection page and their progress will be lost, even if there is only one call open. Currently, when there is only one call open selecting `New Proposal` the user will stay on the proposal creation page, keeping their progress. The behaviour this PR introduces is consistent with when there are multiple calls open.
Users can be be confused and …
> feat: Makes selecting a call when making a propsal always required.

- .gitignore
Add user office frontend e2e cypress tests screenshots to gitignore.
When running test on the local environment we don't necessary what git to keep track of cypress screenshots changes.
Closes: https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/749
Files changed:
gitignore
Manually tested.
> fix:Add user office frontend e2e cypress tests screenshots to gitignore

- apps/user-office-backend/src/datasources/postgres/CallDataSource.ts
CALL_ENDED or CALL_ENDED_INTERNAL events must be retriggered when either call end date or call end internal dates are updated.
When the user officer opens a call after it has previously been closed and triggered the CALL_ENDED event. Proposals submitted after the call end date is updated will not have their workflow updated by the CALL_ENDED event because it would have been triggered already and will not be triggered when the new call ended date expires. The same issue also applies to CALL_ENDED_INTERNAL event.
Both CALL_ENDED or CALL_ENDED_INTERNAL event must be retriggered at the new dates after call dates updates.
- manual tests
https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/731
Files:
- apps/user-office-backend/src/datasources/postgres/CallDataSource.ts
> feat: call events must be retriggered when call dates are extended after being previously closed

- apps/user-office-backend/src/datasources/AdminDataSource.ts
- apps/user-office-backend/src/datasources/postgres/AdminDataSource.ts
This PR aims to fix the issue where the server will throw an exception if trying to update a setting that does not exist. The more resilient approach is to create the setting in case it does not exist.
This PR makes the backend more resilient
https://jira.esss.lu.se/browse/SWAP-2954
> fix: make settings update more resilient  

- .github/dependabot.yml
This PR should fix the failing docker image pushes when dependabot creates PR with branch name containing slash "/". Now it should replace slash "/" separator with hyphen "-".
All dependabot PRs were failing in push action.
Adds dependabot.yml file for dependabot configuration.
> fix: Fixing dependabot PRs and branch names

- .github/workflows/build-push.yml
We have separate deploy jobs for each image. Since October (I'm guessing the monorepo merge?) we've not been running the backend one, so our dev environment was missing out on changes.
Closes https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/796
> chore: trigger both STFC deploy jobs after building develop

- apps/user-office-frontend-e2e/cypress/integration/shipments.ts
- apps/user-office-frontend-e2e/cypress/integration/templates_advanced.ts
- apps/user-office-frontend-e2e/cypress/integration/templates_basic.ts
- apps/user-office-frontend-e2e/cypress/integration/units.ts
- apps/user-office-frontend-e2e/cypress/support/utils.ts
- apps/user-office-frontend-e2e/package-lock.json
- apps/user-office-frontend-e2e/package.json
- apps/user-office-frontend-e2e/tsconfig.json
- apps/user-office-frontend/src/components/common/FileUploadComponent.tsx
- apps/user-office-frontend/src/components/questionary/questionaryComponents/FileUpload/QuestionaryComponentFileUpload.tsx
This PR aims to improve tests and remove duplicates.
1. In the template tests we had duplicate tests that were left after some splitting in multiple files.
2. Remove `cypress-file-upload` package cause it is not needed after cypress introduced `cy.selectFile` command on their own.
> refactor: Remove cypress-file-upload package because cy.selectFile was introduced and do some cleanup of duplicate tests

- apps/user-office-frontend/src/components/questionary/questionaryComponents/NumberInput/QuestionNumberInputForm.tsx
Click empty space should not trigger url redirection
When user accidentally click empty space right below the input field it triggers View/Edit all units button.
apps/user-office-frontend/src/components/questionary/questionaryComponents/NumberInput/QuestionNumberInputForm.tsx
> Fix: click on empty space should not trigger url redirection

- apps/user-office-backend/src/eventHandlers/messageBroker.ts
Add extra information in ProposalMessage.
We will use this information later for creating chatrooms.
https://jira.esss.lu.se/browse/SWAP-2969
Added new fields `oidcSub` and `oauthIssuer` to DTO and populated them with the respective values.
Created type `Member` for common data structure
N/A
> feat: sending extra information in proposal message to create chatroom

- apps/user-office-frontend/src/components/questionary/QuestionaryStepView.tsx
When a user update their proposal (if it's in a call that allows it), they only get messages that the proposal has been "saved", which isn't clear that it has been re-submitted.
Make it more clearer to users that each time they press save and continue  on a submitted proposal , their proposal is being resubmitted.
- Manual test.
Closes: https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/764
Files changed:
- apps/user-office-frontend/src/components/questionary/QuestionaryStepView.tsx
> fix: improve toast success message when saving submitted proposal

- apps/user-office-frontend/src/context/UserContextProvider.tsx
Clicking logout was logging you back in again. The problem was that even though the app tries to redirect to the logout page, it is interrupted because the state of the user object changed, which interrupts and refreshes the page. There is no need to set the state of the application if there is a logout URL because the state of the app will be lost anyway as soon as the URL is opened.
Logout button should log user out of the system
https://jira.esss.lu.se/browse/SWAP-3018
N/A
> fix(auth): logout not working, logs you back in again

- .github/workflows/test-build.yml
The syntax we used to use for specifying node_version appears to not work anymore, and even though v16 is specified pipeline takes node version v18
This PR simplifies the syntax and uses a simple variable to define the node version.
> chore: Fix failure running pipelines

- .github/workflows/test-build.yml
- apps/user-office-backend/package-lock.json
- apps/user-office-backend/package.json
- apps/user-office-backend/src/eventHandlers/messageBroker.ts
This PR changes so that backend does not send message directly to `queues`, but use `exchange`
This helps decouple the services because core should now know who is listening to the events
Message broker that is used by ESS
N/A
> fix: send to exchange instead of direct message queue

- apps/user-office-backend/src/auth/OAuthAuthorization.ts
This PR fixes the return of old user's data after `externalTokenLogin` update of the user.
The old data was returned instead of updated user.
> fix: return the updated user after external token login instead of the old version

- apps/user-office-frontend/src/components/common/FileUploadComponent.tsx
Closes https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/742
The proposal submission system requests upload of science case PDF file for specific proposal template. If the upload file name has additional periods beyond the file extension, the system prevents the upload without reason given. 
To accept upload file name that is supported by browser. 
Manually tested pdf file upload process by using file with name contain periods beyond the file extension.
Amend frontend file FileUploadComponent.tsx to accept file with name contain periods beyond the file extension.
> Fix: Failure of PDF file upload of proposal because the filename contains a period char #742

- apps/user-office-backend/src/resolvers/types/FieldConfig.ts
- apps/user-office-frontend/src/graphql/template/fragment.fieldConfig.graphql
Dynamic multichoice question only makes api call for the first time when question is created, subsequent update on question has no effect to answers. Thats due to missing `externalApiCall` flag on front-end, which is required to make new api call on backend, otherwise BE will always return the result of very first api call.
- e2e
- manual
Dynamic multichoice questionary dropdown does not update option values on question update
> fix : dynamic multichoice add missing field to FE

- apps/user-office-frontend/src/context/UserContextProvider.tsx
- apps/user-office-frontend/src/hooks/common/useDataApi.ts
When a users session expires the user is currently redirected to the OIDC session logout endpoint, the user should instead be redirected to re-login. The user should only be redirected to the OIDC logout on explicit  logout
Fixes confusing behaviour for users that has had session expiring
Locally
SWAP-3111
> SWAP-3111:  Handling session expiration

- Dockerfile.e2e
Part of an update to get the e2e tests running for STFC locally after the Cypress upgrade. Will additonally require https://github.com/isisbusapps/docker-orchestration/pull/438
Part of UserOfficeProject/user-office-project-issue-tracker#862
> Update STFC e2e dockerfile after Cypress upgrade

- apps/user-office-backend/package-lock.json
- apps/user-office-backend/package.json
- apps/user-office-backend/src/asyncJobs/jobs/checkAllCallsEnded.ts
- apps/user-office-backend/src/asyncJobs/jobs/checkCallsReviewEnded.ts
- apps/user-office-backend/src/asyncJobs/jobs/checkCallsSEPReviewEnded.ts
- apps/user-office-backend/src/config/Tokens.ts
- apps/user-office-backend/src/config/dependencyConfigE2E.ts
- apps/user-office-backend/src/config/dependencyConfigESS.ts
- apps/user-office-backend/src/config/dependencyConfigSTFC.ts
- apps/user-office-backend/src/config/dependencyConfigTest.ts
- apps/user-office-backend/src/decorators/EventBus.ts
- apps/user-office-backend/src/eventHandlers/customHandler.ts
- apps/user-office-backend/src/eventHandlers/proposalWorkflow.ts
- apps/user-office-backend/src/events/index.ts
- apps/user-office-backend/src/models/questionTypes/InstrumentPicker.ts
- apps/user-office-backend/src/mutations/InstrumentMutations.ts
This PR addresses the issue that side effects were not run when instrument was assigned to the proposal, because previously onBeforeSave InstrumentPicker questionary component used data source directly
Now it calls the method on InstrumentMutations so that additional business logic is also invoked.
This however required to resolve circular dependency resolving issue, where EventBus tried to resolve some dependencies prematurely. The solution was made that EventBus was moved into dependency container as well
Side effects should be run also when user answers the question with Instrument Picker
Manual tests
E2E tests
> fix: Ensure that side effects when proposal is automatically assigned to instrument are run

- apps/user-office-backend/src/datasources/postgres/UserDataSource.ts
- apps/user-office-backend/src/mutations/ProposalMutations.spec.ts
- apps/user-office-backend/src/mutations/ProposalMutations.ts
Fixes #275 
The check of `users.includes(currentUser.id)` will always return true as `users` contains co-proposers and `getProposalUsers()` returns the PI as well as co-proposers
> Hotfix: fix users not being to update proposals

- apps/user-office-backend/src/datasources/stfc/StfcUserDataSource.ts
- apps/user-office-frontend/src/utils/helperFunctions.ts
PI name and email (in User Officer role on proposals table )information  not showing after view the proposal info and then close that proposal.
Users Officer need to see the PI information on proposals.
Manual 
Closes: https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/876
Files changed:
- apps/user-office-backend/src/datasources/stfc/StfcUserDataSource.ts
- apps/user-office-frontend/src/utils/helperFunctions.ts
> Fix PI name and email not showing in user officer table  after viewing proposal

- apps/user-office-backend/db_patches/0133_NonIntergerGrade.sql
- apps/user-office-backend/src/datasources/postgres/AdminDataSource.ts
This PR aims to add extra safety by wrapping the patch in knex transaction. In case the patch fails the rollback is automatically performed by knex.
This PR also addresses the small issue with db_patch, where db_patch tries to insert app setting. However the appsetting is already added by the code in configureESSEnvironment.ts and configureSTFCEnvironment.ts and since those run before the patches are applied, then there is a conflict when the app setting is inserted. A quick on conflict clause addresses this issue
Make patches more resiliant
SWAP-3456
Patches
> fix: run patches in transaction, and make sure to upsert an appsetting GRADE_PRECISION

- apps/user-office-frontend/src/context/UserContextProvider.tsx
This PR aims to fix the incorrect redirect URL that is used after session expired error handling.
Before if there was a session expired error frontend was redirected to invalid login URL without `redirect_uri` parameter.
- manual tests
> fix: redirect to correct session expired url

- apps/user-office-backend/db_patches/0138_AddProposalTemplateSampleDeclaration.sql
- apps/user-office-backend/src/datasources/mockups/PdfTemplateDataSource.ts
- apps/user-office-backend/src/datasources/postgres/PdfTemplateDataSource.ts
- apps/user-office-backend/src/datasources/postgres/records.ts
- apps/user-office-backend/src/models/PdfTemplate.ts
- apps/user-office-backend/src/mutations/PdfTemplateMutations.spec.ts
- apps/user-office-backend/src/mutations/PdfTemplateMutations.ts
- apps/user-office-backend/src/mutations/TemplateMutations.ts
- apps/user-office-backend/src/resolvers/mutations/CreatePdfTemplateMutation.ts
- apps/user-office-backend/src/resolvers/mutations/UpdatePdfTemplateMutation.ts
- apps/user-office-backend/src/resolvers/queries/PdfTemplatesQuery.ts
- apps/user-office-backend/src/resolvers/types/PdfTemplate.ts
- apps/user-office-frontend-e2e/cypress/e2e/pdfTemplates.cy.ts
- apps/user-office-frontend/src/components/template/PdfTemplateEditor.tsx
- apps/user-office-frontend/src/graphql/template/fragment.template.graphql
- apps/user-office-frontend/src/graphql/template/getPdfTemplate.graphql
- apps/user-office-frontend/src/graphql/template/updatePdfTemplate.graphql
New PDF template field called Sample Declaration have been added alongside Body, Header and Footer. The logic is, if the Sample declaration design html is provided, it will be generated as an attachment with its own bookmark, else, it will not be generated.
To support Sample Declaration
Manually and e2e test
New field called 'template_sample_declaration' in 'pdf_templates' table.
> Swap 3466 support sub templates

- .github/dependabot.yml
Add limitation of open PRs from dependabot to avoid reaching job runners limit and entering a state where we can not run our open PRs workflow correctly.
> chore: limit open PRs from dependabot to avoid reaching job runners limit

- apps/frontend/src/hooks/file/useFilesMetadata.ts
This pull request addresses a race condition issue where the current file list was being overwritten by API call results. To fix this problem, the useFilesMetadata function updates the file list based on its previous value.
The race condition occurred between the API call and the setFiles function call. In some cases, this led to the unintended overwriting of the current file list. By modifying the useFilesMetadata function to consider the previous value, we have resolved this issue and ensured the file list remains consistent.
- Manually
- E2E test (templatesAdvanced.cy.ts: "User can add captions after uploading image/* file" test case / slow cpu)
https://jira.esss.lu.se/browse/SWAP-3572
> fix: useFilesMetadata updates the file list based on the previous file list

- .github/workflows/auto-merge-dependabot.yml
Github job workflow > auto-merge >` Approve patch and minor updates step` expecting `GH_TOKEN` instead of `GITHUB_TOKEN`
```
gh: To use GitHub CLI in a GitHub Actions workflow, set the GH_TOKEN environment variable. Example:
env:
GH_TOKEN: ${{ github.token }}
```
> fix: rename auto merge GITHUB_TOKEN to GH_TOKEN

- apps/frontend/src/components/proposal/ProposalQuestionaryDetails.tsx
- apps/frontend/src/components/questionary/QuestionaryDetails.tsx
- apps/frontend/src/components/review/ProposalQuestionaryReview.tsx
- apps/frontend/src/hooks/questionary/useQuestionary.ts
The "QuestionaryDetails" component has a new prop, 'questionaryData.' If it is provided, it will be used instead of refetching the questionary data.
In the "ProposalQuestionaryReview", the proposal information is provided, so it can be used in the "QuestionaryDetails"
- Manually
> fix: Multiple data fetch on questionary details in the proposal review

- apps/backend/src/factory/pdf/proposal.ts
Fixed the issue of technical review information not showing up in the proposal pdf. 
In the Proposal PDF, the template can be configured to display the technical review. This was working for sometime. Now it is stopped working. While debugging, it was figured out that the tech review data is not being passed for few user roles. Since we have a user level condition in the PDF template, we can provide the tech review data from user office no matter what the user role is and the pdf template can now control who can see and who can't see. 
Manually
> Tech review data added to pdf generation immaterial of the user role

- apps/backend/src/datasources/stfc/StfcUserDataSource.ts
Closes https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/869 https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/910
Add a mapping from STFC roles to SEP rolls. Needed for testing on dev, 
Turning on the feature fully will be done later with modification to e2e test to make sure they can still run in STFC mode.
> Add SEP roles for STFC

- apps/backend/src/datasources/postgres/ProposalDataSource.ts
- apps/backend/src/resolvers/queries/ProposalsQuery.ts
- apps/e2e/cypress/e2e/templatesBasic.cy.ts
- apps/frontend/src/components/template/ProposalTemplatesTable.tsx
This PR adds functionality to show the modal popup when a number of proposals for the template is clicked. This opens a window to list all the associated proposals to the template.
Sometimes user officer want's to know which proposal exactly is using the template.
Manually,
Added e2e tests
SWAP-800
> feat: Show which proposals has been created with the proposal template

- apps/frontend/src/components/call/CallGeneralInfo.tsx
- apps/frontend/src/components/common/RefresListIcon.tsx
- apps/frontend/src/components/questionary/questionaryComponents/SampleDeclaration/QuestionSampleDeclarationForm.tsx
- apps/frontend/src/components/questionary/questionaryComponents/SampleDeclaration/QuestionTemplateRelationSampleDeclarationForm.tsx
The aim of this Pull Request (PR) is to enhance the user experience during the creation of sample declaration questions. It introduces a new feature: a refresh list button and a link titled "View all templates" on the sample declaration question form. This link directs users to the sample declaration ESI (Experiment safety input) templates page. This addition is particularly helpful in situations where there are no existing sample declaration ESI templates available, or if the author wishes to add a new template. Once a new template is added, the author can return to the original form and click 'refresh' to view the newly added template.
Additionally, this PR reuses the RefreshIcon from calls, therefore it is refactored and moved outside into a new component so that it can be reused …
> feat: As a user officer I want to create sample declaration template easier

- apps/backend/src/factory/pdf/proposal.ts
- apps/e2e/cypress/e2e/proposalAdministration.cy.ts
Fixes https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/768
As a user officer, I would like the proposal PDF filename changed to RB_SURNAME_YYYY format so that it's easier to manage
Manual
e2e tests
https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/768
Proposal pdf filename is changed to RB_SURNAME_YYYY format
- [x ] I have added tests to cover my changes.
> Proposal pdf filename is changed to RB_SURNAME_YYYY format

- .github/workflows/test-build.yml
The update involves changing job dependencies to avoid unnecessary job runs.
If the "build" job fails, then there is no need to run other tests.
> ci: "build" job needs to be run successfully before "test_backend" and "e2e" jobs will run

- apps/backend/src/datasources/postgres/ProposalDataSource.ts
- apps/e2e/cypress/e2e/proposals.cy.ts
- apps/frontend/src/components/proposal/ProposalTableOfficer.tsx
Fixes https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/881
The user office proposal table is not able to sort by the following column principal investigator name ,PI email, submitted and notified. When we select any of the above columns, the table show blank data.
Manual
https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/881
Fields 'notified' and 'submitted' is added to the known fields list of proposal view.
Sorting for email and name column is disabled as per discussion.
> Fix sorting issue for proposal table

- apps/frontend/nginx.conf
This PR aims to enable `gzip` compression in the `nginx` server on the frontend.
There was no compression enabled before and this quite important to reduce the amount of data sent over the network especially for larger files.
- manually tests loacally
https://jira.esss.lu.se/browse/SWAP-3660
> feat: enable gzip compression in nginx

- apps/e2e/cypress/e2e/pdfTemplates.cy.ts
- apps/frontend/src/components/template/CreateTemplate.tsx
- apps/frontend/src/components/template/PdfTemplateDefaultData.tsx
When creating new pdf template, create default dummy pdf data for preview. 
At the moment, when the user officer creates a new pdf template, the body, header, footer etc are all empty and the preview throws an error page. Inserting default values during pdf creation will solve this issue. 
Manually
> improvement: Added default pdf data while creating pdt template.

- apps/frontend/src/components/questionary/questionaryComponents/Embellishment/QuestionEmbellishmentForm.tsx
- apps/frontend/src/components/questionary/questionaryComponents/Embellishment/QuestionTemplateRelationEmbellishmentForm.tsx
As a user officer, I should be able to add links/images to embellishment questions.
Fixes https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/830
When adding an embellishment question, you cannot interact with any of the embellishment pop up windows. This stops you from being able to click/type in it to add things like links, images, etc.
Manual. Screenshots attached.
https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/830
Added fix to prevent Bootstrap dialog from blocking focusing.
> Enabling interaction with embellishment pop up windows

- apps/backend/db_patches/db_seeds/0002_InstrumentScientiests.sql
This PR changed e2e database patch instrument scientists username.
Currently, in the e2e database patch, two instrument scientists are injected with an identical user name, which makes it hard to see if the dropdown list sorting feature is working or not in the new feature cypress test for scheduler.
> Fix: Changed test db patch scientist user name

- .github/workflows/test-build.yml
This PR modifies the SDK caching strategy due to issues it causes when running the workflows.
The SDK caching has been causing problems when running the workflows, which hampers the smooth running of our tasks and operations. Changing the caching strategy to only be reused in the current run and attempt will lead to more stable and reliable workflows.
- Changed the key of actions/cache to be unique only per run and attempt in the GitHub workflows for caching the frontend SDK.
- manual tests
[https://jira.esss.lu.se/browse/SWAP-3652](https://jira.esss.lu.se/browse/SWAP-3652)
> feat: cache the frontend sdk per each run and attempt only to reduce the issues related to it in the actions

- apps/backend/src/mutations/ProposalMutations.ts
- apps/backend/src/resolvers/mutations/ImportProposalMutation.ts
- apps/backend/src/resolvers/mutations/UpdateProposalMutation.ts
Changes done as part of https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/955. New field is added to graphql mutation to update the actual submitted date of proposals while running the proposal migration script.
Manually tested.
Part of the issue https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/955 will be fixed with this PR. Proposal migration scripts will be changed and committed after this.
New field created date is added to import proposal and update proposal queries.
> Add created date field to query for proposal migration script

- apps/frontend/src/components/review/ProposalGrade.tsx
- apps/frontend/src/components/review/ProposalTechnicalReview.tsx
Closes [978](https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/978)
Renamed the button text from "Save" to "Save and Submit"
The feedback from the FAP meeting as the current display could encourage saving with the presumption that reviewing is complete.
Manually
> Rename Save button to Save and Submit when adding a review

- apps/backend/src/queries/UserQueries.ts
- apps/backend/src/resolvers/types/BasicUserDetails.ts
Closes [980](https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/980)
The Internal Reviewer is granted access to view Principal Invetigators name and email.
Initially the PI name and email columns were displaying empty values in the Internal Reviewer dashboard and only the Proposal Information was only displaying the PI name as shown below:
These changes allow the Internal Reviewer to view PI name and email in both the dashboard and the Proposal Information tab:
Manually
[980](https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/980)
Gave the Internal Reviewer role access to `UserQueries` and `BasicUserDetails` 
N/A
> Allow Internal Reviewer to view PI name and email

- apps/frontend/Dockerfile
This PR addresses a permission issue in the frontend Dockerfile by copying `build-version.txt` from the build stage.
This change is necessary to resolve a permission issue that was arising due to the Dockerfile trying to write the `build-version.txt` in a directory where it didn't have write permissions. This change fixes the issue by creating the `build-version.txt` file in the build stage and copying it over to the necessary directory, thereby avoiding the need for write permissions.
- The `build-version.txt` file is now created in the build stage with the help of the `RUN` command.
- The `ARG BUILD_VERSION=<unknown>` command has been shifted to the build stage.
- The `COPY` command is now used to copy the `build-version.txt` file from the build stage to the required directory in the …
> Fix: copy build-version.txt from the build stage to address a permission issue in the frontend Dockerfile

- apps/frontend/src/components/instrument/AssignedScientistsTable.tsx
- apps/frontend/src/components/instrument/InstrumentTable.tsx
Add beam line manager details when viewing an instrument in the instrument page.
Manual Testing
Closes https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/987
- apps/frontend/src/components/instrument/AssignedScientistsTable.tsx
- apps/frontend/src/components/instrument/InstrumentTable.tsx
> Add beam line manager details when viewing an instrument in the instrument page

- apps/backend/src/datasources/postgres/CallDataSource.test.ts
- apps/backend/src/datasources/postgres/CallDataSource.ts
Closes UserOfficeProject/user-office-project-issue-tracker#937
This fixes logic for updating a call's `call_ended` and `call_ended_internal` flags. These flags are only used for determining whether to fire the `CALL_ENDED` and `CALL_ENDED_INTERNAL` events respectively. We find calls where call ended = false, set the flag to true, then fire the event. The previous logic would mean that the values were always left false, so the events would keep firing at each check and we'd notice them in the STFC logs.
The new logic says that:
- The flag can be explicitly set to true or false
- When a call is updated with a future call end date, the call ended flag is changed to false.
- If the call was closed (flag was true), this ensures the event will still fire now that it's open.
- If the call was …
> Fix call_ended event firing

- apps/backend/src/datasources/postgres/UserDataSource.ts
- apps/e2e/cypress/e2e/proposals.cy.ts
- added missing implementation for getUsersByUserNumbers function to adapt PR #469. 
- added test to ensure principal investigator in the proposal userofficer table not to be empty.
After PR #469, the proposal table fails to load user information with ESS config due to missing getUsersByUserNumbers implementation despite all the e2e successes. This PR aims to fix that.
- e2e
- manual
> fix: included ESS getUsersByUserNumbers implementation

- apps/e2e/cypress/e2e/FAPs.cy.ts
- apps/frontend/src/components/fap/Proposals/FapProposalsAndAssignmentsTable.tsx
Closes [981](https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/981)
Added a `Reviews` column in the `FAP Proposals and Assignments` table which displays the number of proposals reviewed out of total number of proposals to review.
Initially, the system required to click the `Show Reviews` drop down to check if proposals were graded or not. Having this feature makes it easier for FAP members to quickly check if there are any outstading proposals that require grading especially for calls like ISIS which require two reviewers per proposal.
Manually
> 981 display summary of scored proposals

- .github/workflows/test-build.yml
Github actions runners are no longer supporting node 16 https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/ and the cache action was running 16 by default so I have just updated it: https://github.com/actions/cache/releases/tag/v4.0.0.
> chore: Update cache action to v4

- apps/frontend/src/components/proposal/ProposalTableInstrumentScientist.tsx
- apps/frontend/src/components/proposal/ProposalTableOfficer.tsx
Closes: [Improve proposal search by waiting for user to finish typing search term #920](https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/920)
Looked for debounceInterval and changed the value of it from 400 to 600.
Was changed to improve the quality of use from the users, as the query would search as the user was typing in the proposal search bar. Was a beginner issues to get my practice with local testing and get more of an understanding with the code within the repos used for the website. 
Used user.localhost and office.localhost to see the local code changes on the machine.
Manually tested the search bar while also console.log the searchText input from the user, to see if the code was still searching before the user was allowed to finish typing.
Just a …
> Improve proposal search by waiting for user to finish typing search term 

- apps/frontend/src/components/common/CenteredAlert.tsx
The default mui alert message overflow value is auto, which hid the ellipsis with a scrollbar
I tweaked my local frontend instance so that successful external auth wouldn't redirect you to a different page. Adding this CSS change had the following effect in browser:
Closes UserOfficeProject/issue-tracker#927
> fix(css): make ellipsis visible when using external auth

- apps/backend/src/eventHandlers/messageBroker.ts
This PR introduces a feature to send proposal messages when a proposal is accepted. 
The change is required to ensure that relevant parties are notified and can take appropriate action when a proposal is accepted. This enhances the communication flow within the system.
- An event listener for `PROPOSAL_ACCEPTED` event has been added in the `messageBroker.ts` file. 
- Upon the occurrence of this event, `getProposalMessageData` function is called to fetch the necessary message data.
- This data is then sent as a message to the relevant parties.
> feat: send proposal message upon PROPOSAL_ACCEPTED event

- apps/backend/src/resolvers/types/Shipment.ts
- apps/frontend/src/components/questionary/questionaryComponents/ShipmentBasis/QuestionaryComponentShipmentBasis.tsx
In the Shipment model, the scheduledEventId column is nullable. But in the graphql query `getShipments`, the column is defined as non nullable in the class `Shipment`. Due to this confict, the graphql query is failing. The class has been changed to make the column as nullable and made it aligned as per the table structure. 
Fix graphql query
Manually
getShipments() graphql query
Changes in class `Shipment`
> fix: changed scheduledEventId to be nullable

- apps/frontend/src/components/questionary/questionaryComponents/QuestionDependencyList.tsx
- apps/frontend/src/models/questionary/QuestionaryFunctions.ts
- Fix a bug where if you add an OR dependency to a question, and then remove it, it will not show up in a proposal or questionary preview. This was because with either an OR or AND dependency, it was still checking whether an empty list of dependencies were completed, but passing for AND and failing for OR. Made the check skip if the dependency list if empty.
- After the last dependency is removed from a question, reset the operator to AND. Thought this would be nice for consistency since we default to AND when first adding.
Manual testing questionary preview and creating a proposal. Checking database operator value.
Fixes https://github.com/UserOfficeProject/issue-tracker/issues/1006
> fix: question fails to show with removed dependency

- apps/frontend/src/components/call/CallsTable.tsx
Fix the sorting of dates in the calls table by comparing dates instead of strings.
Closes UserOfficeProject/issue-tracker#1010
> fix: calls table sorting order of dates

- apps/backend/db_patches/0150_UpdateEmailInviteFeature.sql
Closes: UserOfficeProject/issue-tracker/issues/999
Adds a db patch to correct the description of the `EMAIL_INVITE` feature.
Fixes a minor typo.
Tested manually
> fix: correct email invite feature typo

- apps/backend/src/factory/xlsx/stfc/StfcFapDataRow.ts
Closes https://github.com/UserOfficeProject/issue-tracker/issues/1038
This PR allows blank reviews in the STFC FAP export.
This change is required to handle cases where an STFC FAP export contains reviews that are blank. 
- Updated the `populateStfcRow` function in the `StfcFapDataRow.ts` file. Now it first checks if a review comment exists before attempting to strip HTML from it. This prevents errors when a review comment is blank.
> fix: allow blank reviews on stfc fap export

- apps/backend/package-lock.json
- apps/backend/package.json
- apps/backend/src/resolvers/mutations/AdministrationProposalMutation.ts
- apps/e2e/cypress/e2e/experiments.cy.ts
- apps/e2e/cypress/e2e/proposalEsi.cy.ts
- apps/e2e/cypress/e2e/shipments.cy.ts
- apps/e2e/cypress/e2e/visits.cy.ts
- apps/frontend/package-lock.json
- apps/frontend/package.json
- apps/frontend/src/graphql/proposal/administrationProposal.graphql
This PR upgrades the duo-validation package version and adjusts the related backend and frontend code accordingly.
The change was necessary due to the upgrade of the duo-validation package from version 4.0.4 to 5.0.0. This upgrade introduced breaking changes that required adjustments in the backend and frontend code. The upgrade enhances the validation mechanisms, improving the overall quality and reliability of the application.
1. Upgraded duo-validation in both package.json and package-lock.json files from version 4.0.4 to 5.0.0.
2. Removed statusId field from AdministrationProposalArgs class and replaced it with finalStatus field of type ProposalEndStatus.
3. Adjusted the tests and inputs in various files to comply with the changes introduced by the duo-validation upgrade. The affected …
> fix: fixing tests and inputs after validation upgrade

- apps/backend/db_patches/0153_AlterFapProposals.sql
This fix the issue where we are failing to delete proposals which are in draft . 
We are now using the instrument picker which automatically populate the `fap_proposals` table and we need to cascade deletion to the mentioned table .
Manual
https://github.com/UserOfficeProject/issue-tracker/issues/1056
Added files:
1. 0153_AlterFapProposals.sql
> fix: cascade proposal deletion to fap proposals table

- apps/backend/src/datasources/stfc/StfcProposalDataSource.ts
Closes: https://github.com/UserOfficeProject/issue-tracker/issues/1058
This PR addresses an issue of duplicate proposals appearing in the STFC Instrument Scientist Proposal page.
This change is required to ensure that each proposal appears only once in the STFC Instrument Scientist Proposal page, thus eliminating confusion and improving user experience.
update stfc instrument sci data source
> fix: duplicate proposals in stfc instrument sci proposal page

- apps/frontend/src/components/template/PdfTemplateDefaultData.tsx
- docker-compose.yml
Added /preview to the allowed paths in the traefik ruleset and fixed the pdf preview issue. Also changed port from 4501 to 4500 in the default pdf template, since the factory usually runs in 4500.
Using docker-compose, the preview pdf was not working, bcoz the path /preview was not whitelisted in the traefik. 
Manually
PDF Preview issue
> fix: add preview to the allowed paths in the traefik ruleset

- apps/frontend/src/components/proposal/ProposalContainer.tsx
- apps/frontend/src/models/questionary/useEventHandlers.ts
Fixes https://github.com/UserOfficeProject/issue-tracker/issues/906
After deleting an answer/template from a subtemplate question, the state of deleted templates is not getting updated correctly for some scenarios. Because of which we get an error 'Can not delete genericTemplate because of insufficient permissions' when we try to submit the form after adding another answer or going to previous page and coming back. 
Another issue was that, if we have 2 subtemplate questions, after an answer deletion from any of the subtemplate, when we try to add another answer to one of the sub templates, then whole data from second sub template disappears. 
Manually
Update to not consider deletedtemplates again while reinitializing the form.
apps/frontend/src/components/proposal/ProposalContainer.tsx …
> fix: genericTemplate deletion error

- apps/backend/src/config/dependencyConfigDefault.ts
This PR updates the `dependencyConfigDefault.ts` to use auto-upgrade of database patches.
The change is required to automate the database patching process. It simplifies the patch management by automatically applying the necessary updates.
- Replaced `PostgresAdminDataSource` with `PostgresAdminDataSourceWithAutoUpgrade` in `dependencyConfigDefault.ts`.
- Updated the token mapping for `AdminDataSource` to use `PostgresAdminDataSourceWithAutoUpgrade`.
These changes ensure that the system uses the version of `AdminDataSource` that supports automatic database patch upgrades, reducing manual intervention and potential errors.
> fix: update dependencyConfigDefault.ts to use autoupdate of db_pacthes

- apps/backend/db_patches/0151_MultipleFapPerProposal.sql
This PR introduces a database patch to clean up stale `fap_assignments` and `fap_reviews` that are not linked to any `fap_proposal`.
This change is required to maintain data integrity and avoid orphan records in `fap_assignments` and `fap_reviews` tables, which can lead to confusion and potential errors in future data operations.
1. The `fap_assignments` table is updated to set `fap_proposal_id` for existing records. Any records that do not have a corresponding `fap_proposal` are deleted.
2. The `fap_reviews` table is updated similarly, setting `fap_proposal_id` for existing records and deleting any records that do not have a corresponding `fap_proposal`.
3. The `fap_proposal_id` column in both tables is then set to NOT NULL to enforce data integrity moving forward. …
> fix: database patch fix to cleanup old fap_assignments and fap_reviews that are not related to any fap_proposal

- apps/backend/db_patches/0151_MultipleFapPerProposal.sql
- apps/backend/db_patches/0156_ImproveProposalTableViewForMultiFaps.sql
- apps/backend/src/datasources/stfc/StfcProposalDataSource.ts
- apps/backend/src/resolvers/types/ProposalView.ts
- apps/frontend/src/components/proposal/ProposalTableInstrumentScientist.tsx
This PR improves and fixes the proposal table view for multi FAP proposals.
The change is required to enhance the proposal table view for multi FAP proposals by providing a more efficient and structured way to display complex data related to different FAPs associated with each proposal. It also fixes the incorrect assignment of technical review assignee ID.
1. A new database patch is introduced to improve the proposal table view for multi FAP proposals. This patch creates a new view with a better structure to handle proposals associated with multiple FAPs.
2. The StfcProposalDataSource file has been updated to correct the assignment of the technical review assignee ID.
3. The ProposalView file has been updated to make the fields `instrumentId` and `technicalReviewAssignee` nullable, …
> fix: improve and fix the proposal table view for multi FAP proposals

- apps/backend/src/datasources/postgres/FapDataSource.ts
Hotfix so only submitted proposals appear in FAP export
We had a support ticket in where proposals that were expired or in draft were showing up in the FAP data exports. This change makes it so only submitted proposals show up there.
> fix: only submitted proposals in fap

- apps/backend/src/workflowEngine/index.ts
This PR introduces a fix to prevent workflow errors when the `proposal_deleted` event is triggered.
This change is necessary to handle the scenario when a proposal gets deleted. Previously, the deletion of a proposal was causing workflow errors. This PR aims to prevent those errors and maintain the integrity and smooth operation of the workflow engine.
- Introduced a check for the `proposal_deleted` event in the workflow engine. If this event is triggered, the workflow engine will log an informative message and cease further operation. This prevents any errors that might occur due to the deletion of the proposal.
- Imported and used the logger from '@user-office-software/duo-logger' to log the information when the `proposal_deleted` event is triggered. …
> fix: prevent workflow errors when proposal_deleted event is fired

- apps/e2e/cypress/e2e/proposalAdministration.cy.ts
- apps/frontend/src/components/proposal/ProposalAdmin.tsx
This PR prevents the administration of a proposal without an assigned instrument.
This change was necessary to ensure the proper functioning of the application and prevent users from making changes to proposals that are not yet assigned to an instrument.
- Added a condition to check if an instrument is assigned to a proposal before allowing administration. 
- If no instrument is assigned, a message is displayed to inform the user that the proposal has to be assigned to an instrument before it can be administered. 
- Added an end-to-end test to validate this behavior.
[https://jira.esss.lu.se/browse/SWAP-4081](https://jira.esss.lu.se/browse/SWAP-4081)
> fix: prevent proposal administration without instrument assigned

- apps/backend/src/mutations/FapMutations.ts
- apps/e2e/cypress/e2e/FAPs.cy.ts
This PR aims to fix the issue of automatic FAP assignment when an instrument is assigned to multiple calls.
This change is required to ensure the correct FAP is automatically assigned to a proposal when multiple instruments are assigned to a proposal. This is crucial for maintaining consistency and correctness in our data.
- Modified the logic in `FapMutations.ts` to correctly filter and map FAP instruments based on the callId.
- Added a new test case in `FAPs.cy.ts` to verify that a proposal is automatically assigned to the correct FAP when multiple instruments are assigned to a proposal.
[https://jira.esss.lu.se/browse/SWAP-4098](https://jira.esss.lu.se/browse/SWAP-4098)
> fix: auto FAP assignment when instrument is assigned to multiple calls

- apps/backend/src/datasources/FapDataSource.ts
- apps/backend/src/datasources/mockups/FapDataSource.ts
- apps/backend/src/datasources/postgres/FapDataSource.ts
- apps/backend/src/mutations/FapMutations.ts
- apps/backend/src/resolvers/mutations/FapMeetingDecisionMutation.ts
- apps/backend/src/resolvers/types/FapProposal.ts
- apps/e2e/cypress/e2e/FAPs.cy.ts
- apps/frontend/src/components/fap/MeetingComponents/FapInstrumentProposalsTable.tsx
- apps/frontend/src/components/fap/MeetingComponents/FapMeetingInstrumentsTable.tsx
- apps/frontend/src/graphql/fap/submitFapMeetingDecisions.graphql
Closes https://github.com/UserOfficeProject/issue-tracker/issues/1048
This pull request introduces the feature of mass submitting completed meeting decisions.
This feature was added to allow users to submit multiple completed meeting forms at once, making the process more efficient and less time-consuming.
1. Implemented a function in the FapDataSource for submitting Fap meetings.
2. Added a resolver for the new function in FapMutations.
3. Created a new mutation in FapMeetingDecisionMutation to handle the submission of Fap meeting decisions.
4. Updated the FapProposal type.
5. Added a test case for the new feature in FAPs.cy.ts. 
This feature has been tested using the end-to-end testing suite, specifically the test case added in FAPs.cy.ts. The tests ensure that multiple completed …
> feat: mass submit completed meeting decisions

- apps/backend/src/queries/FapQueries.ts
Closes: https://github.com/UserOfficeProject/issue-tracker/issues/1078
Allows users with API keys to fetch FAP proposals, which is an explicit option when selecting API key permissions.
This makes actual API key behaviour more closely align its expected behaviour.
Tested manually
- `apps/backend/src/queries/FapQueries.ts` Adds check for API key use to `getFapProposals`
> fix: api keys can get fap proposals

- apps/frontend/src/components/call/CallPage.tsx
- apps/frontend/src/components/experiment/ExperimentPage.tsx
- apps/frontend/src/components/fap/FapPage.tsx
- apps/frontend/src/components/fap/FapsPage.tsx
- apps/frontend/src/components/institution/InstitutionPage.tsx
- apps/frontend/src/components/instrument/InstrumentsPage.tsx
- apps/frontend/src/components/pages/HelpPage.tsx
- apps/frontend/src/components/pages/OverviewPage.tsx
- apps/frontend/src/components/pages/PageEditor.tsx
- apps/frontend/src/components/proposalBooking/InstrSciUpcomingExperimentTimesTable.tsx
- apps/frontend/src/components/proposalBooking/UserExperimentsTable.tsx
- apps/frontend/src/components/sample/SampleSafetyPage.tsx
- apps/frontend/src/components/settings/apiAccessTokens/ApiAccessTokensPage.tsx
- apps/frontend/src/components/settings/appSettings/AppSettingsPage.tsx
- apps/frontend/src/components/settings/features/FeaturesPage.tsx
- apps/frontend/src/components/settings/proposalStatus/ProposalStatusesPage.tsx
- apps/frontend/src/components/settings/proposalWorkflow/ProposalWorkflowsPage.tsx
- apps/frontend/src/components/settings/unitList/UnitTablePage.tsx
- apps/frontend/src/components/technique/TechniquesPage.tsx
- apps/frontend/src/components/template/EsiPage.tsx
- apps/frontend/src/components/template/FeedbackTemplatesPage.tsx
- apps/frontend/src/components/template/GenericTemplatesPage.tsx
- apps/frontend/src/components/template/PdfTemplatesPage.tsx
- apps/frontend/src/components/template/ProposalTemplatesPage.tsx
- apps/frontend/src/components/template/QuestionsPage.tsx
- apps/frontend/src/components/template/SampleEsiPage.tsx
- apps/frontend/src/components/template/SampleTemplatesPage.tsx
- apps/frontend/src/components/template/ShipmentTemplatesPage.tsx
- apps/frontend/src/components/template/VisitTemplatesPage.tsx
- apps/frontend/src/components/user/PeoplePage.tsx
This PR extends the width of all pages with tables to full-width.
The change is required to enhance the user experience by providing a more spacious and clear view of the table data, thereby improving readability and data comprehension.
- Modified the `StyledContainer` component's `maxWidth` property to `false` across multiple pages. This change allows the container to take up the full available width.
- This modification has been applied to pages like `CallPage.tsx`, `ExperimentPage.tsx`, `FapPage.tsx`, `InstitutionPage.tsx`, `InstrumentsPage.tsx`, `HelpPage.tsx`, `OverviewPage.tsx`, `PageEditor.tsx`, `SampleSafetyPage.tsx`, `ApiAccessTokensPage.tsx`, `AppSettingsPage.tsx`, `FeaturesPage.tsx`, `ProposalStatusesPage.tsx`, `ProposalWorkflowsPage.tsx`, `UnitTablePage.tsx`, `EsiPage.tsx`, …
> feat: make all pages with tables to expand full-width

- apps/frontend/src/components/proposal/ProposalTableOfficer.tsx
Closes https://github.com/UserOfficeProject/issue-tracker/issues/1083
Instead of row data, the export function is changed to consider all the selected proposals.
When you select a list of proposals and "Export proposals in Excel", it will only include the first 20 proposals in the exported spreadsheet. All proposals need to show in the spreadsheet for it to be useful and to avoid repetition.
Manually
https://github.com/UserOfficeProject/issue-tracker/issues/1083
apps/frontend/src/components/proposal/ProposalTableOfficer.tsx
> fix: proposal export doesn't include all selected proposals

- apps/backend/src/middlewares/factory/zip.ts
- apps/e2e/cypress/e2e/proposalAdministration.cy.ts
- apps/frontend/src/context/DownloadContextProvider.tsx
This PR handles the case when no attachments are found in zip middleware and displays an appropriate message.
This change was required to provide clear feedback to the user when no attachments are found. It helps in improving the user experience by avoiding confusion that could arise from the absence of an appropriate response.
1. Added a check in `zip.ts` middleware to return a 404 status and 'NO_ATTACHMENTS' message when no attachments are found.
2. Modified `proposalAdministration.cy.ts` to ensure that the 'No attachments found' alert is displayed when no attachments are present.
3. Updated `DownloadContextProvider.tsx` to enqueue a snackbar message 'No attachments found' when the error 'NO_ATTACHMENTS' is caught.
[https://github.com/UserOfficeProject/issue-tracker/issues/1112](https:// …
> chore: handle case when no attachments are found in zip middleware and display appropriate message

- apps/frontend/src/components/call/CreateUpdateCall.tsx
Adding fix to set seconds and milliseconds to 0 while loading default values for call creation page.
It was observed that while a call is created, an extra 59 seconds and/or 59 milliseconds is being added for all end time fields. Because of which, the call ends are being considered with 1 hour delay while the every hour job for checking the call closure/internal call closure runs. 
This is caused because, while we populate the default values for call start and call end, the call end was defined as currentdate.endOfTheDay(). Therefore, the seconds and milliseconds will be 59.59+00. Even if the user officer changes the hour and minutes(which are the only options available to choose), the seconds and milliseconds remain unchanged.
Manually
Fixes …
> fix: remove the extra 59 seconds added to the timestamp for call end-time fields

- apps/frontend/src/components/template/PdfTemplateEditor.tsx
- apps/frontend/src/components/template/PdfTemplateEditorViewer.tsx
Added resizing option to the PDF viewer
In the PDF viewer, both the code editor and the previewer lie side by side. In some viewports, it is quite difficult to use the editor as both the editor and previewer shrinks due to the viewport. 
Manually
PDF Editor UX
Added custom zoom plugin to the PDF viewer.
> feat: resizing option in pdf viewer enabled

- apps/frontend/src/components/questionary/questionaryComponents/InstrumentPicker/QuestionaryComponentInstrumentPicker.tsx
Closes https://github.com/UserOfficeProject/issue-tracker/issues/1158
As agreed in sprint planning, this is a hotfix to remove the `None` option from the instrument picker dropdown.
> fix: remove none instrument picker option

- apps/frontend/src/components/proposal/ProposalTableInstrumentScientist.tsx
Closes https://github.com/UserOfficeProject/issue-tracker/issues/1160
This is a hotfix to resolve the problem of the next page button is greyed out and disabled, so scientists can only view 5, 10 or 20 proposals (using the "rows per page" dropdown) and cannot view more.
> fix: resolve scientist proposal page next page button is greyed out and disabled problem #1160

- apps/backend/src/models/questionTypes/RichTextInput.ts
Image width/height attributes are removed from img tags in TinyMCE Rich Text answers (when images are allowed in template configuration). 
Fix the issue described above.  
Manual tests. 
Add missing attributes to the proper html sanitizer.
Add missing attributes to the proper html sanitizer.
N/A
> fix: add missing attributes for img tags in TinyMCE editors

- apps/backend/db_patches/0158_AddFAPReviewTemplate.sql
The creator_id value was incorrect when creating a new FAP review template. This commit fixes the issue by setting the correct creator_id value to 0 which is the Service account.
> fix: update creator_id in FAP review template creation

- apps/backend/src/models/questionTypes/InstrumentPicker.ts
- apps/backend/src/mutations/InstrumentMutations.ts
- apps/e2e/cypress/e2e/proposals.cy.ts
- apps/frontend/src/components/questionary/questionaryComponents/InstrumentPicker/QuestionaryComponentInstrumentPicker.tsx
closes: UserOfficeProject/issue-tracker#1170
HOTFIX
This PR fixes an issue where the instrument picker was not properly removing instruments from a proposal.
The current behavior of the instrument picker led to a problem where removed instruments were still appearing in the proposal, causing confusion and potential inaccuracies in the proposal data. This change is required to ensure that when an instrument is removed, it is reflected correctly in the proposal.
- Added code to identify instruments on a proposal that need to be removed based on the updated selection in the instrument picker.
- Modified the condition to trigger the removal of instruments from a proposal, ensuring it occurs whenever there are instruments to remove.
- Adjusted the value assignment in the instrument picker …
> fix: instrument picker not removing instruments from proposal

- apps/backend/src/datasources/postgres/FileDataSource.ts
- apps/backend/src/factory/StfcDownloadService.ts
Refs https://github.com/UserOfficeProject/issue-tracker/issues/1163
- Fix the postgres error we're seeing for invalid large-object descriptor
- The problematic part was `proposalPdfData.emit('end');` as `proposalPdfData.pipe(res);` has already closed the stream at that point
- Refactor the db retrieval to add more robust error handling
- Add logging so that we can see when a proposal was downloaded via postgres and whether it was successful or not
> fix: serving STFC PDFs from Postgres

- apps/backend/db_patches/0162_UpdateOldInstrumentPickerAnswersv2.sql
This is a hotfix for a db patch that is already in dev. It needs to get onto STFC prod soon to prevent user issues.
I cherry-picked the two commits from PR https://github.com/UserOfficeProject/user-office-core/pull/772
> fix: instrument picker answer formats

- apps/backend/src/auth/OAuthAuthorization.ts
Some user attributes are only updated after the second login of the user (first login will create the user in the users table, the second login will update the existing record).
It is confusing that some user attributes will only be set after the second login. 
Manual testing + e2e.
Synchronize the inserted / updated user attributes. 
Update upsert method in OAuthAuthorization.ts.
N/A
- [ x] I have added tests to cover my changes.
- [ x] All relevant doc has been updated
> fix: insert all available user information at creation time

- .github/workflows/build-push.yml
This commit adds a new workflow job to trigger the generation of the SDK for the user-office-scheduler repository. The workflow is triggered when changes are made to the develop branch.
This commit addresses the need to automatically trigger the SDK generation process for the user-office-scheduler repository when changes are made to the develop branch.
> chore: add a job to trigger SDK generation in user-office-scheduler

- apps/e2e/cypress/e2e/predefinedMessages.cy.ts
- apps/frontend/src/components/common/predefinedMessages/PredefinedMessagesModal.tsx
Fixed Predefined message window delete and create, by resetting the form value properly during deletion
When deleting the predefined message, the form was not clearing. Bcoz of which, the creation thrown error due to the deleted message's id not getting cleared
Attached e2e
- [*] I have added tests to cover my changes.
> fix: predefined delete message issue fixed

- apps/frontend/src/components/instrument/CreateUpdateInstrument.tsx
- apps/frontend/src/components/internalReview/CreateUpdateInternalReview.tsx
Add missing user role filters when searching for internal reviewers / instrument scientists. 
It is possible to add internal reviewer / instrument scientist for a proposal / instrument without having the proper role. 
Manual test & e2e
Add missing roles for the user lookup.
Code changes in frontend.
N/A
- [ x] I have added tests to cover my changes.
- [ x] All relevant doc has been updated
> fix: user search for instrument scientist and internal reviewer

- apps/backend/src/datasources/stfc/StfcFapDataSource.ts
- apps/backend/src/datasources/stfc/StfcInstrumentDataSource.ts
- apps/backend/src/datasources/stfc/StfcProposalDataSource.ts
- apps/backend/src/datasources/stfc/StfcTechniqueDataSource.ts
- apps/backend/src/factory/xlsx/stfc/StfcFapDataRow.ts
In STFC we use an external service to get user details, and cache results to improve performance. I noticed that we're logging statistics for multiple parallel instances of these, which means we're not getting the full benefit of those caches, as different parts of the app may be requesting the same data from the slow external source instead of using already requested and cached data.
I browsed to local pages where the updated data sources would be used and they seemed to load fine. Other than that I'm just relying on the test suite to check for regressions.
Closes UserOfficeProject/issue-tracker#1188
> fix: prevent multiple instances of the StfcUserDataSource being created

- .github/workflows/test-build.yml
Swaps the array of cypress patterns for an array of objects so we can append a neat identifier to the name of the uploaded screenshot archive. This way we when multiple sections of the e2e tests fail, all of them should be able to upload screenshots. At present only the first to fail can, and subsequent failures complain that 
> Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run
Syntax was taken from https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/running-variations-of-jobs-in-a-workflow#example-using-a-multi-dimension-matrix
In this PR's first run of the tests enough were flaky and failed to give multiple screenshot archive uploads using the new …
> test: allow mutliple test runners to upload cypress screenshots

- apps/backend/src/auth/StfcUserAuthorization.ts
- apps/backend/src/datasources/stfc/StfcProposalDataSource.ts
- apps/backend/src/datasources/stfc/StfcUserDataSource.ts
Instead of caching responses from the STFC users service, cache the requests. This way if a piece of external data is being requested, and additional requests for it come in while that first one is being made, we don't have to make repeated requests to the external service.
When loading the user officer homepage with empty caches in my local setup, this reduced the number of queries made to get user data from 155 to 56.
I also removed an unnecessary & unused initialisation of the STFC users datsource, which caused unnecessary duplicate cache statistics to be logged. I believe this must have come from merge conflict resolution some time after I got rid of them in #820
We use a comparitively slow external service to provide user data, and cache responses to improve performance. However, if …
> perf: cache stfc user service requests instead of responses

- apps/backend/src/auth/OAuthAuthorization.ts
This PR resolves the issue of handling undefined `preferred_username` in `OAuthAuthorization`.
The change was required because the code was breaking when `preferred_username` was undefined. This PR provides a solution to this problem by setting a default value.
The changes introduced in this PR are:
- A default value is set for `preferred_username` in the event that it is undefined. The default value is an empty string.
- This change is implemented in two places within the `OAuthAuthorization` class where `preferred_username` is being utilized.
The above changes ensure the smooth functioning of the code even when `preferred_username` is undefined.
> fix: handle undefined preferred_username in OAuthAuthorization

- apps/frontend/src/components/fap/FapsTable.tsx
- apps/frontend/src/graphql/fap/fragment.fapMinimal.graphql
- apps/frontend/src/graphql/fap/getFaps.graphql
- apps/frontend/src/graphql/fap/getFapsMinimal.graphql
- apps/frontend/src/graphql/fap/getMemberFaps.graphql
- apps/frontend/src/hooks/fap/useFapsData.ts
Closes https://github.com/UserOfficeProject/issue-tracker/issues/1098
This PR optimizes the 'get faps' query by fetching only the necessary data, improving the performance of the application. For the first pass at this issue, I saw that the `useFapsData` hook is only ever used to get a very small amount of FAP data so I have modified it to only request a much smaller subset of FAP data. In the future if we may a query that gets all the FAP data but I think we should then implement a separate query for that that get exactly the data it needs. 
Here is a table of what `useFapsData` used to fetch and what of that data was used:
The 'get faps' query was fetching excessive data, leading to slower performance. To improve the speed and efficiency of our application, it was necessary to limit the …
> perf: fetch less data on the get faps query

- apps/e2e/cypress/e2e/predefinedMessages.cy.ts
- apps/e2e/cypress/e2e/templatesBasic.cy.ts
Closes: https://github.com/UserOfficeProject/issue-tracker/issues/1226
This PR fixes broken tests and refines testing workflow in the application.
The change is required to ensure that all tests are running as expected and to refine the testing workflow to avoid false positives and negatives, thereby improving the reliability of our testing suite.
- Removed `.only` from some test cases to ensure all tests run as expected.
- Added a `beforeEach` function to skip a certain test if the corresponding feature is not enabled.
- Added pauses and checks in certain test cases to ensure that the UI has finished loading before proceeding with the test.
- Fixed a test case where a template could not be deleted if it was associated with any Questionary. …
> chore: fix broken tests

- apps/backend/src/auth/SampleAuthorization.ts
User Authorization is responsible for verifying the roles of various user. However in Sample Authorization, it has its own verification method, which is a duplicated of what User Authorization has. The duplicated method has been removed from the Sample Authorization, ensuring User Authorization is the only source of identifying roles. 
Avoiding duplication
Manually
> chore: optimised sample safety auth by using user auth for discovering sample safety user

- apps/frontend/src/components/questionary/questionaries/fapReview/FapReviewQuestionaryWizardStep.ts
The FAP reviewer has no write access to FAP reviews after end of call.
The bug was introduced in the FAP review template implementation. 
Manual and e2e tests. 
Fall back to the original logic: only disable FAP reviews for FAP reviewers if the review has already been submitted. 
Fix condition in FapReviewQuestionaryWizardStep.ts
N/A
> fix: remove wrong condition from fap reviewer grade access

- apps/backend/src/factory/DownloadService.ts
- apps/backend/src/factory/xlsx/proposal.ts
- apps/backend/src/middlewares/factory/xlsx.ts
- apps/e2e/cypress/e2e/xpress.cy.ts
- apps/frontend/src/components/xpress/XpressProposalTable.tsx
- apps/frontend/src/context/DownloadContextProvider.tsx
- apps/frontend/src/graphql/proposal/getTechniqueScientistProposalsBasic.graphql
- apps/frontend/src/hooks/proposal/useDownloadXLSXProposal.ts
This PR introduces a feature that allows users to export Xpress proposals. 
The need for this feature arose from the necessity to provide users with a way to export proposal data for offline usage and further analysis. This feature enhances the usability of the platform and provides additional value to our users.
- Added an option to export Xpress proposals in the `DownloadService.ts` file.
- Implemented the collection of proposal data for XLSX export in the `proposal.ts` file.
- Created a new route in the `xlsx.ts` file to handle the export of the collected data.
- Added e2e tests in the `xpress.cy.ts` file to ensure the feature works as expected.
- Updated the frontend `XpressProposalTable.tsx` file to include the export option in the UI. 
In addition to the unit tests that have been …
> feat: add option to export xpress proposals

- apps/backend/src/datasources/postgres/ReviewDataSource.ts
- apps/frontend/src/components/review/ProposalTableReviewer.tsx
This PR optimizes the proposal reviewer table by refining the status check and improving the selection functionality.
The changes in this PR are required to handle the edge case where the status could be undefined and to manage the selection state more effectively, thus enhancing the user experience and functionality of the proposal reviewer table.
- In the `ReviewDataSource.ts` file, the status check has been improved to handle both `null` and `undefined` cases.
- In the `ProposalTableReviewer.tsx` file, the `selection` state is now derived from `searchParams` rather than being a constant. This allows it to update dynamically based on changes to the `searchParams`.
- The dependency array in the `useEffect` hook has been updated to include `searchParams` to ensure that changes to these …
> fix: proposal reviewer table fixes

- apps/frontend/src/components/questionary/questionaryComponents/FapReviewBasis/createFapReviewBasisValidationSchema.ts
This was changed with the introduction of review templates. Since it is not in a React component, I can't use the setting context and since the frontend has no env file/variables I can't find a way of parameterising this for different facilities. 
We need this change now, so I am putting this in, and we can discuss how we parameterise validation schemas later if that is ok?
> fix: fap reviews comment character limit

- apps/frontend/src/components/common/proposalFilters/InstrumentFilter.tsx
- apps/frontend/src/components/experiment/ExperimentFilterBar.tsx
- apps/frontend/src/components/instrument/AssignProposalsToInstruments.tsx
- apps/frontend/src/components/proposal/ProposalFilterBar.tsx
- apps/frontend/src/components/proposal/ProposalPage.tsx
- apps/frontend/src/components/proposal/ProposalTableInstrumentScientist.tsx
- apps/frontend/src/components/proposal/ProposalTableOfficer.tsx
- apps/frontend/src/components/proposalBooking/InstrSciUpcomingExperimentTimesTable.tsx
- apps/frontend/src/components/review/ProposalTableReviewer.tsx
- apps/frontend/src/graphql/instrument/getInstrumentsMinimal.graphql
- apps/frontend/src/graphql/instrument/getMyInstrumentsMinimal.graphql
- apps/frontend/src/graphql/instrument/instrumentMinimal.fragment.graphql
- apps/frontend/src/hooks/instrument/useInstrumentsMinimalData.ts
Closes: https://github.com/UserOfficeProject/issue-tracker/issues/1223
This PR optimizes the fetching of instrument data by introducing a minimal version of instrument data fetching. 
This change is required to improve the performance of the application by minimizing the amount of data fetched when full instrument data is not necessary.
1. Introduced a minimal version of instrument data fetching in various components where full instrument data was previously fetched.
2. Updated the types and usages of instrument data in various components to use the minimal version.
3. Replaced the calls to `useInstrumentsData()` with `useInstrumentsMinimalData()` in various components.
This change will reduce the load on the server and improve the user experience by speeding up the loading times. …
> perf: stop overfetching of instrument data

- apps/frontend/src/components/common/proposalFilters/CallFilter.tsx
- apps/frontend/src/components/proposal/ProposalFilterBar.tsx
- apps/frontend/src/graphql/call/getCallsByInstrumentScientist.graphql
- apps/frontend/src/hooks/call/useInstrumentScientistCallsData.ts
Closes: UserOfficeProject/issue-tracker#1250
This PR optimizes the query for retrieving calls by Instrument Scientist. 
Comparing the new query against the old on STFC prod:
| Old | New |
| ------------- | ------------- |
| 2.404904s | 0.127819s | 
| 2.129852s | 0.112924s | 
| 1.974664s | 0.119315s | 
| 3.013225s | 0.109058s | 
| 3.062653s | 0.107943s | 
| 2.059708s | 0.105477s | 
| 2.124660s | 0.109718s | 
| 4.493919s | 0.133059s | 
| 2.233179s | 0.146521s | 
| 3.068420s | 0.194828s | 
The change is required to improve the performance of the application. It solves the problem of unnecessary data being fetched and processed, which slows down the application.
- The calls prop in `CallFilterProps` and `ProposalFilterBarProps` has been modified to only pick 'shortCode' and 'id' fields.
- The …
> perf: optimize instr sci call query

- apps/frontend/src/components/common/FileLink.tsx
- apps/frontend/src/context/DownloadContextProvider.tsx
Closes: UserOfficeProject/issue-tracker#1260
This PR introduces a download dialog to the FAP document store.
The change was necessary to provide users with feedback when they initiate a file download, preventing confusion and enhancing the user experience.
- Added a new state variable 'isLoading' to track the download status in `FileLink.tsx`.
- Created a download dialog component in `DownloadContextProvider.tsx` and made it visible when a file is being downloaded.
- Integrated the dialog with the file download function in `FileLink.tsx`. Now, whenever a user clicks a file link, the download dialog pops up until the download is complete.
Please note that the 'cancel' function in the download dialog is optional and will only appear if provided. …
> feat: add download dialog to fap document store

- apps/frontend/src/components/AppToolbar/AppToolbar.tsx
This removes the User Office heading to make pages clearer to identify, as agreed in sprint planning.
The "User Office" text was unnecessarily repeated on every page, making the title verbose and causing visual clutter. This change simplifies the title, improving readability and user experience.
- The "User Office" prefix has been removed from the toolbar title. Now, the title only contains 'Dashboard' when on the home page, and the respective header for other pages.
Only manual testing that the page heading shows on each page. If there is anything else to be aware of, please let me know.
Closes https://github.com/UserOfficeProject/issue-tracker/issues/1236
> refactor: remove User Office heading text

- apps/backend/src/datasources/postgres/ProposalDataSource.ts
- apps/e2e/cypress/e2e/templatesBasic.cy.ts
- apps/frontend/src/components/proposal/ProposalAttachmentDownload.tsx
- apps/frontend/src/components/template/AnswerCountDetails.tsx
- apps/frontend/src/components/template/ProposalTemplatesTable.tsx
- apps/frontend/src/graphql/proposal/getProposalsMinimal.graphql
- apps/frontend/src/hooks/proposal/useProposalsData.ts
Connects the template filter option to the API call in the frontend, fixes the implementation of that filter in the backend, and optimises the query it uses.
I extended the e2e test for the proposals by template popup to check that the filtering is being applied properly
Closes https://github.com/UserOfficeProject/issue-tracker/issues/1252
> fix: prevent crashes when viewing a template's proposals

- apps/backend/src/factory/pdf/proposal.ts
This PR refactors the way we retrieve call details for proposal downloads, enhancing the overall code quality and error handling. 
Previously, the call details retrieval for proposal downloads was not optimally structured and lacked proper error handling. This could result in unexpected behaviors if a call was not found for a proposal. This refactor aims to improve the robustness of the code and provide better error handling.
1. Added an error condition to throw an error if the call associated with a proposal is not found, ensuring the code fails fast and predictably in such a scenario.
2. Removed redundant call fetching in the 'collectProposalPDFData' function, simplifying the function's logic. The call details are fetched once at the beginning and used throughout the function.
3. The …
> fix: refactor getting call details for proposal downloads

- apps/backend/src/factory/xlsx/fap.ts
another hotfix sorry, to make the spreadsheets tech review comment useable
> fix: strip html from tech rev comment in fap export

- apps/frontend/src/components/xpress/ProposalScientistComment.tsx
- apps/frontend/src/components/xpress/XpressProposalTable.tsx
This PR introduces tool tips in the Xpress management page to improve user experience.
The change was required to provide important contextual information to users, guiding them on how to interact with various elements on the Xpress management page, hence enhancing usability and user experience.
1. Tooltips have been added to the "Proposal Scientist Comment" section in `ProposalScientistComment.tsx`, providing users with important guidelines on how to interact with comments.
2. Tooltips have been added to the "Instrument" and "Status" columns in `XpressProposalTable.tsx`, helping users understand the rules and conditions associated with changing the status of a proposal and experimental area selection.
3. The layout and structure of some code blocks have been modified to accommodate these …
> feat: add tool tips in Xpress management page

- apps/frontend/src/components/user/PeopleTable.tsx
closes https://github.com/UserOfficeProject/issue-tracker/issues/1240
Changes the message that's displayed when you search for the email of a user that's already been added to a proposal/visit/FAP from "User is already on the proposal" to the more generic "User has already been added".
PeopleTable is used in several contexts so the error message so be more generic.
Tested manually
`apps/frontend/src/components/user/PeopleTable.tsx line 432` - Error message has been changed
> refactor: changes user already added error message

- apps/backend/src/mutations/FapMutations.ts
Closes https://github.com/UserOfficeProject/issue-tracker/issues/1311
Allows users with API keys to carry out certain FAP mutations.
- `apps/backend/src/mutations/FapMutations.ts` Allows API keys to `assignReviewersToFap`, `assignFapReviewersToProposals`, `removeMemberFromFap`, `removeMemberFromFapProposal`
Manually
> fix: allow api keys for certain fap mutations

- apps/e2e/cypress/e2e/FAPs.cy.ts
This pull request removes the "only" function from the 'Fap meeting exports test' context in the Cypress end-to-end test suite.
The "only" function in Cypress is used during development to run a specific set of tests exclusively, ignoring all other tests. Leaving this function in the codebase can unintentionally skip important tests, leading to undetected bugs. This change ensures that the entire test suite is run, maintaining the integrity of our testing process.
- Removed the "only" function from the 'Fap meeting exports test' context in the file `apps/e2e/cypress/e2e/FAPs.cy.ts`. This ensures that the test suite runs all tests as intended.
> chore: remove only

- apps/frontend/src/components/questionary/questionaryComponents/GenericTemplate/GenericTemplateDefinition.tsx
- apps/frontend/src/components/questionary/questionaryComponents/GenericTemplate/QuestionGenericTemplateForm.tsx
- apps/frontend/src/components/questionary/questionaryComponents/GenericTemplate/QuestionTemplateRelationGenericTemplateForm.tsx
This PR introduces an "isRequired" option for generic template questions in the application. 
Previously, there was no way to mandate the input for generic template questions. This was causing issues as some responses were left blank by users, leading to incomplete data. This feature aims to solve this problem by allowing the option to make these questions required.
- Added a new "isRequired" option in the `genericTemplateDefinition` in `GenericTemplateDefinition.tsx`. This checks if the configuration requires an answer and adjusts the schema accordingly.
- Added a new checkbox in `QuestionGenericTemplateForm.tsx` and `QuestionTemplateRelationGenericTemplateForm.tsx` to allow users to mark a question as required.
https://github.com/UserOfficeProject/issue-tracker/issues/1180
> feat: add isRequired option for generic template questions

- apps/backend/db_patches/0168_AddCoProposerClaims.sql
- apps/backend/package-lock.json
- apps/backend/package.json
- apps/backend/src/auth/InviteAuthorizer.ts
- apps/backend/src/config/Tokens.ts
- apps/backend/src/config/dependencyConfigDefault.ts
- apps/backend/src/config/dependencyConfigE2E.ts
- apps/backend/src/config/dependencyConfigELI.ts
- apps/backend/src/config/dependencyConfigESS.ts
- apps/backend/src/config/dependencyConfigSTFC.ts
- apps/backend/src/config/dependencyConfigTest.ts
- apps/backend/src/datasources/CoProposerInviteDataSource.ts
- apps/backend/src/datasources/ProposalDataSource.ts
- apps/backend/src/datasources/mockups/CoProposerInviteDataSource.ts
- apps/backend/src/datasources/mockups/ProposalDataSource.ts
- apps/backend/src/datasources/postgres/CoProposerInviteDataSource.ts
- apps/backend/src/datasources/postgres/ProposalDataSource.ts
- apps/backend/src/datasources/postgres/records.ts
- apps/backend/src/decorators/ValidateArgs.ts
- apps/backend/src/models/CoProposerInvite.ts
- apps/backend/src/mutations/InviteMutations.spec.ts
- apps/backend/src/mutations/InviteMutations.ts
- apps/backend/src/resolvers/mutations/CreateInviteMutation.ts
This pull request adds co-proposer claim to the invite
Although 20+  files have been touched, the main changes are in the following files
- apps/backend/db_patches/0168_AddCoProposerClaims.sql
- apps/backend/src/auth/InviteAuthorizer.ts
- apps/backend/src/datasources/postgres/CoProposerInviteDataSource.ts
- apps/backend/src/mutations/InviteMutations.ts
Now it is possible to not only add a role, but also a co-proposer claim. This allows to create invites which when claimed assigns user a role.
1. Added a new table `co_proposer_invites` in the PostgreSQL database to store co-proposer invite data.
2. Created the `InviteAuthorizer.ts` to include a new `InviteAuthorization` class to handle co-proposer invite authorization.
3. Updated package.json to use latest duo-validation for argument …
> feat: add co proposer claim to invite

- apps/backend/package.json
- apps/backend/src/config/dependencyConfigTest.ts
- apps/backend/src/config/ess/configureGrayLogLogger.ts
Info messages are now bold, error messages appear in red, and warnings are shown in yellow. These changes improve the readability of log outputs in the console making it easier to spot the error outputs.
Relates to: https://github.com/UserOfficeProject/user-office-lib/pull/209
The changes were made to enhance the clarity of log outputs, making it easier to distinguish between different types of log messages at a glance, ultimately aiding in debugging and monitoring.
- Added ANSI color codes to format INFO, ERROR, and WARN log levels.
- Refactored the log method in ConsoleLogger to apply the appropriate color formatting.
> feat: colorize log output

- apps/backend/package-lock.json
Update's the backend's package-lock.json by running npm install.
I believe this should fix a bunch of failing github action builds which seem to be using an outdated version of the backend's npm modules cache with an old version of our logging library. This cache is only updated when package-lock.json is updated, which the logger update PR didn't do https://github.com/UserOfficeProject/user-office-core/pull/933
> chore: update backend package-lock.json

- apps/backend/src/decorators/EventBus.ts
This PR is a tweak to make sure the `resultKey` and `event` is not defined if it is a test environment , because it is not used in test.
1. Moved the definition of `resultKey` inside the check for `NODE_ENV !== 'test'`, ensuring it is only defined when it is needed.
2. Adjusted the creation of the `event` object to be inside the check for `NODE_ENV !== 'test'`, as it now relies on the `resultKey` that is defined inside this check.
> fix: refactor event logging to ensure resultKey and event is defined before usage

- apps/backend/src/mutations/FileMutations.ts
- apps/frontend/src/components/common/FileUploadComponent.tsx
This PR introduces a new feature that prevents the uploading and saving of empty files (0 bytes) to the system.
The change is required to enhance the error handling mechanism of our file upload process. Previously, the system allowed empty files to be uploaded and saved, which could lead to data inconsistency and potential errors down the line.
1. Added a condition to check the file size in the backend (FileMutations.ts). If the file size is 0 bytes, the system will reject the file and return an error message.
2. Updated the frontend (FileUploadComponent.tsx) to handle the new rejection case. If a user tries to upload an empty file, they will see a rejection message stating "File size is 0 bytes".
3. Updated the error message displayed to the user to include issues with file size, in …
> fix: handle empty files

- apps/frontend/src/components/fap/FapGradeGuide.tsx
- apps/frontend/src/components/fap/General/FapGeneralInfo.tsx
Closes https://github.com/UserOfficeProject/issue-tracker/issues/1264
This PR restricts non-user officers from editing the custom grade guide.
This change is required to ensure that editing permissions for the custom grade guide are strictly controlled and limited to user officers, providing a safeguard against unauthorized modifications.
1. Updated the access rights in the FapGradeGuide component to only include the UserRole.USER_OFFICER.
2. Disabled the editing of the custom grade guide in the FapGeneralInfo component when the user does not have access rights or when a call is executing.
> fix: stop non user officers from editing custom grade guide

- apps/backend/src/datasources/stfc/StfcProposalDataSource.ts
- apps/e2e/cypress/e2e/genericTemplates.cy.ts
- apps/e2e/cypress/e2e/instruments.cy.ts
Close https://github.com/UserOfficeProject/issue-tracker/issues/1365
The PR includes enhancements to the proposal data source and test cases, improving the overall functionality and reliability of the application.
The changes were necessary to enable technical review tests in STFC mode and to address certain issues related to proposal filtering and test case execution.
1. In `StfcProposalDataSource.ts`, the proposal filter logic has been updated to allow filtering of proposals with multiple instruments. This expands the filtering capabilities of the application.
2. In `genericTemplates.cy.ts`, a test case related to sub-template cloning has been updated, enhancing the robustness of our test suite.
3. In `instruments.cy.ts`, the setup for instrument-related test cases has been modified to …
> test: turn on tech review tests stfc mode and clean up only

- apps/backend/package-lock.json
- apps/backend/package.json
- apps/e2e/cypress.config.ts
- apps/e2e/cypress/e2e/FAPs.cy.ts
- apps/e2e/cypress/e2e/pdfTemplates.cy.ts
- apps/e2e/cypress/support/fileUtilTasks.ts
- apps/e2e/package-lock.json
- apps/frontend/package-lock.json
This PR updates the muhammara library to version 5.3.0 and the npm engine to version 10.9.2. as well as updates some E2E tests that started to fail due to different race conditions
The previous version of muhammara (4.1.0) and npm engine (10.8.2) were outdated. Updating these ensures that we are using the latest features, security updates, and bug fixes provided by these versions.
- Updated muhammara from version 4.1.0 to 5.3.0. This may introduce new features, improve performance, and fix potential bugs present in the previous version.
- Updated npm engine from version 10.8.2 to 10.9.2. This ensures compatibility with the latest npm features and updates.
- Updated dependencies of muhammara to their latest respective versions. This includes updates to "@mapbox/node-pre-gyp", …
> chore: update muhammara to version 5.3.0 and npm engine to 10.9.2

- apps/backend/src/resolvers/types/Sample.ts
This PR improves the questionary resolver for Samples in the backend.
The previous implementation was using deprecated function call. This upgrade should address the issue reported in SWAP-4581 if it still existed.
1. Import `GraphQLError` from 'graphql' to handle errors in a GraphQL-compliant way.
2. Modify the `Questionary` field resolver in `SampleResolver` to not use the deprecated `getQuestionaryOrDefault` method
[https://jira.esss.lu.se/browse/SWAP-4581](https://jira.esss.lu.se/browse/SWAP-4581)
> fix: improve questionary resolver for Samples

- apps/backend/src/queries/ProposalQueries.spec.ts
- apps/backend/src/queries/ProposalQueries.ts
ensure final status is always returned regardless of proposal notification
This change ensures that the final status is always returned, regardless of whether the proposal has been notified. Previously, the return behavior depended on the notification status, which could lead to inconsistencies in response handling.
This fix standardizes the response behavior by always returning the final status. It prevents potential issues where consumers of the API or system logic depend on the final status being available.
> fix: ensure final status is always returned regardless of proposal notification

- apps/backend/src/config/Tokens.ts
- apps/backend/src/config/dependencyConfigDefault.ts
- apps/backend/src/config/dependencyConfigE2E.ts
- apps/backend/src/config/dependencyConfigELI.ts
- apps/backend/src/config/dependencyConfigESS.ts
- apps/backend/src/config/dependencyConfigSTFC.ts
- apps/backend/src/config/dependencyConfigTest.ts
- apps/backend/src/eventHandlers/index.ts
- apps/backend/src/eventHandlers/logging.ts
- apps/backend/src/eventHandlers/messageBroker.ts
- apps/backend/src/statusActionEngine/emailActionHandler.ts
- apps/backend/src/statusActionEngine/rabbitMQHandler.ts
- apps/backend/src/statusActionEngine/statusActionUtils.ts
This PR refactors the existing email action handler and prevents it from publishing messages to RabbitMQ.
This change is required to address the bug.
1. Created a new LoggingHandler and added it to the dependency configuration.
2. Refactored the email action handler to call the new LoggingHandler and the existing EmailEventHandler directly, instead of publishing messages to RabbitMQ.
3. Refactored the event handlers to use the new LoggingHandler and removed the now-unused createPostToQueueHandler function.
Previously, the EmailActionHandler was sending an event tothe  event bus to reach the logging handler and add some logs, but as a side-effect it reached postToQueueHandler which was set to listen to the same event
The logic has been changed so that EmailActionHandler does not post a …
> fix: bugfix for mistakenly invoking  rabbitMQ status action when emailAction is selected

- apps/backend/db_patches/0177_AddInstrumentIdToTechRevInPropsalTableView.sql
deleted the outdated patch, that led to error, since it is depending on the table that does not exist. replaced the outdated one with newer one with latest run number
After merging the PR https://github.com/UserOfficeProject/user-office-core/pull/978, the system started to fail while running db patches. Apparently, this is bcoz of the db patch file, that became outdated due to increased commit activities. As it became outdated, the patch has gone unaware of the table rename(proposal_statuses to statuses) and hence the deployment of systems started failing. As an effort of quick fix, the patch has been renamed to make it latest in the chronological order. As a long fix, we will discuss further on how to tackle this situation. 
Manually
> fix: deleted the outdated patch, that led to error

- apps/frontend/src/utils/user.ts
This PR aims to address the issue where if preferred name is null, the output of getFullUserNameWithInstitution returns "null Lastname (institution)"
The bug stems from how the code is checking whether user.preferredname exists. In the ternary operator, the expression " `${user.preferredname}` " is executed, which converts the value of preferredname to a string even if it is null. Since template string conversion of a null value produces the string "null", which is a non-empty string and thus truthy in JavaScript/TypeScript, the code always takes the branch that uses preferredname even when it's actually null. 
Locally
> fix: address getFullUserNameWithInstitution returning "null" as return value

- apps/backend/db_patches/0177_AddTechnicalReviewInstrumentNotNull.sql
- apps/frontend/src/components/review/TechnicalReviewSummary.tsx
It should not be possible to set `instrument_id` to `null` in `technical_review` table. When `technical_review` is crated it does not allow null values, and backend model `TechnicalReview` expects this value to not be `null`. If it is `null` the graphql exception will be thrown.
This PR makes sure that inconsistent data can not be stored in the database. 
Note: while investigating I found out that there is unnecessary optional chaining in the frontend `apps/frontend/src/components/review/TechnicalReviewSummary.tsx` and given the small scope of this PR i took a liberty to address it with this PR.
Improve data integrity
[https://jira.esss.lu.se/browse/SWAP-4582](https://jira.esss.lu.se/browse/SWAP-4582)
> feat: add DB constraint instrumentID not null for technical_review

- apps/backend/src/datasources/postgres/ProposalDataSource.ts
This PR fixes a bug in the `searchText` use in `jsonb_path_exists()` function.
The current implementation of the search functionality in the `jsonb_path_exists()` function does not properly handle special characters, leading to exceptions when searching the proposals table (see exception below). This PR introduces a change to escape special characters. Due to syntax requirements of Knex I had to also change the way jsonPathPattern is constructed
```json
{
"exception": {
"name": "error",
"message": "select *, count(*) OVER() AS full_count from \"proposal_table_view\" inner join \"users\" on \"users\".\"user_id\" = \"proposal_table_view\".\"principal_investigator\" where (proposal_id ILIKE $1 or title ILIKE $2 or proposal_status_name ILIKE $3 or \"users\".\"email\" ilike $4 or …
```
> fix: bugfix for searchText use in jsonb_path_exists()

- apps/backend/src/loaders/BasicUserDetailsLoader.ts
- apps/backend/src/loaders/UsersLoader.ts
Hotfix release:
The user details were also being cached internally by a dependency DataLoader, apart from our normal caches. And these record seems to be staying there for the entire time the particular pod/app is up. This PR is to disable this internal caching for now, as this will not be reflecting any user details changes (first name, lastname etc) until a pod/app is restarted.
> fix: disable DataLoader internal caching

- apps/backend/db_patches/0178_MergeFapReviewsFapAssignments.sql
- apps/backend/src/datasources/FapDataSource.ts
- apps/backend/src/datasources/mockups/FapDataSource.ts
- apps/backend/src/datasources/mockups/ReviewDataSource.ts
- apps/backend/src/datasources/postgres/FapDataSource.ts
- apps/backend/src/datasources/postgres/ReviewDataSource.ts
- apps/backend/src/datasources/postgres/records.ts
- apps/backend/src/models/Review.ts
- apps/backend/src/mutations/FapMutations.ts
- apps/backend/src/resolvers/mutations/SaveReviewerRankMutation.ts
- apps/backend/src/resolvers/types/Review.ts
- apps/frontend/src/components/fap/Proposals/FapAssignedReviewersTable.tsx
- apps/frontend/src/graphql/fap/setReviewerRank.graphql
Closes: https://github.com/UserOfficeProject/issue-tracker/issues/1231
This PR merges the Fap Reviews and Fap Assignments tables into one, they served the same purpose and needed to be updated simultausly. 
The Fap Reviews and Fap Assignments tables had similar structures and were being used for similar purposes, leading to redundancy. Merging these tables eliminates this redundancy, simplifies the database structure and makes it easier to manage and manipulate data. 
1. Created a new SQL script to merge the Fap Reviews and Fap Assignments tables, copying data from the Fap Assignments table to the Fap Reviews table and then dropping the Fap Assignments table.
2. Updated the FapDataSource.ts file to reflect the changes in the database structure. The methods that previously interacted with …
> refactor: merge fap reviews and fap assignment table

- apps/e2e/cypress/e2e/visits.cy.ts
- apps/e2e/cypress/support/utils.ts
- apps/e2e/cypress/types/utils.d.ts
- apps/frontend/src/components/proposalBooking/ActionButton.tsx
- apps/frontend/src/components/proposalBooking/CancelBadge.tsx
- apps/frontend/src/hooks/proposalBooking/useActionButtons.tsx
This PR introduces the 'cancelled' state to the action buttons and uses it for the visit registration.
The change is required to provide a visual representation of a 'cancelled' state in the visit registration, as it wasn't very clear why is the icon disabled.
Additionally the hovering the icon now shows the tool tip, which was not visible before.
Manually and updated e2e tests.
[https://jira.esss.lu.se/browse/SWAP-4649](https://jira.esss.lu.se/browse/SWAP-4649)
> feat: add 'cancelled' state to action buttons and update related tests

- apps/frontend/src/components/visit/VisitStatusIcon.tsx
This PR updates icons for visits that are visible by user officer
Previously icons were a little misleading especially SUBMITTED state icon which was empty rectangle.
Now icons are more descriptive and following the same language what user sees that redish dot means it needs action
> fix: update visit status icons for better clarity and consistency

- apps/backend/src/auth/questionary/VisitQuestionaryAuthorizer.ts
- apps/backend/src/mutations/VisitMutations.spec.ts
- apps/backend/src/mutations/VisitMutations.ts
- apps/backend/src/resolvers/mutations/RequestVisitRegistrationChangesMutation.ts
- apps/e2e/cypress/e2e/visits.cy.ts
- apps/frontend/src/components/experiment/ExperimentVisitsTable.tsx
- apps/frontend/src/components/questionary/questionaries/visitRegistration/VisitRegistrationQuestionaryDefinition.ts
- apps/frontend/src/components/questionary/questionaries/visitRegistration/VisitRegistrationWizardStep.ts
- apps/frontend/src/components/visit/VisitRegistrationReview.tsx
- apps/frontend/src/graphql/visitRegistration/requestVisitRegistrationChanges.graphql
- apps/frontend/src/hooks/proposalBooking/useActionButtons.tsx
This PR implements the "Request Change" functionality for visits.
The change is required to allow User Officers to request changes to a visit, if the specified dates are not feasible. 
1. Making sure visit can modified in both states 'DRAFTED' or 'CHANGE_REQUESTED'.
2. Added new tests to cover the change as well as covering some lacking functionality for visits
3. Added E2E test
[https://jira.esss.lu.se/browse/SWAP-4652](https://jira.esss.lu.se/browse/SWAP-4652)
> feat: implement Request Change functionality for visits

- apps/backend/db_patches/0180_AddFapReviewerNotifiedEvent.sql
Closes: https://github.com/UserOfficeProject/issue-tracker/issues/1394
After https://github.com/UserOfficeProject/user-office-core/pull/1006 fixed the checkCallsFapReviewEndedJob we got a massive error spike of db errors as the FAP_REVIEWER_NOTIFIED event was trying to be added to the proposals-events table but the column does not exist. This PR just adds it.
I checked the other Application events and this was the only one that could be added to the proposals-events table what was missing ..... as far as I can tell.
> fix: add fap reviewer notified to proposal events table

- apps/backend/src/datasources/FapDataSource.ts
- apps/backend/src/datasources/mockups/FapDataSource.ts
- apps/backend/src/datasources/postgres/FapDataSource.ts
- apps/backend/src/resolvers/types/Fap.ts
- apps/backend/src/resolvers/types/FapReviewers.ts
Closes [#1398](https://github.com/UserOfficeProject/issue-tracker/issues/1398)
This change updates the logic of how proposal counts are displayed for FAP members. Previously, the proposal count was being aggregated across multiple FAPs, causing the same member to show the combined proposal count across all FAPs they belong to. With this update, the proposal count is now FAP-specific, ensuring that each FAP's proposal count is correctly displayed for the respective member.
This change is required because the previous logic was incorrectly summing proposal counts across multiple FAPs. For example, if a user is assigned 2 proposals in FAP1 and 3 proposals in FAP2, the system was showing 5 proposals in both FAP1 and FAP2, which was inaccurate. The new logic ensures the proposal count is …
> fix: amend code to allow fap specific proposal count

- apps/backend/db_patches/0181_BackfillSubmittedDate.sql
Adds a database patch to fill in missing values from the submitted_date column in the proposals table using values from the event log.
It ensures that our data is consistent, simplifying any queries we perform so that they don't have to be aware of historic ways to store/query submission dates.
I've run the patch against my local install, using a combination of manually inserted dummy events, and complete copies of our production database.
Closes https://github.com/UserOfficeProject/issue-tracker/issues/1353
> fix: backfill the submitted date field in the proposals table

- apps/backend/db_patches/0182_AddImpersonatingUserIdToEventLogs.sql
- apps/backend/src/datasources/EventLogsDataSource.ts
- apps/backend/src/datasources/postgres/EventLogsDataSource.ts
- apps/backend/src/decorators/EventBus.ts
- apps/backend/src/eventHandlers/logging.ts
- apps/backend/src/events/applicationEvents.ts
- apps/backend/src/models/EventLog.ts
- apps/backend/src/mutations/UserMutations.ts
- apps/e2e/cypress/e2e/eventLogs.cy.ts
- apps/frontend/src/components/review/ProposalReviewContent.tsx
- apps/frontend/src/components/user/RoleTable.tsx
- apps/frontend/src/components/user/UpdateUserInformation.tsx
Closes https://github.com/UserOfficeProject/issue-tracker/issues/1406
This PR ensures that the event log correctly reflects actions taken by an impersonating user, rather than attributing those actions to the impersonated user. It also explicitly mentions impersonated actions in the event logs which provides accurate accountability.
Previously, the event logs would misleadingly show the impersonated user as the actor for actions, obscuring the identity of the actual user taking those actions. 
This PR adds a new Cypress test to verify that the correct user (impersonator) is recorded in the event logs when actions are taken during an impersonation session.
1. Introduced an `impersonatingUserId` field in the `EventLogsDataSource` and implemented logic to detect impersonation, ensuring the …
> fix: add impersonation logs

- apps/backend/src/decorators/EventBus.ts
- apps/e2e/cypress/e2e/FAPs.cy.ts
When Selecting Instruments through Instrument Picker, the corresponding FAP,(if associated), is supposed to be attached to the corresponding Proposal through Event mechanism. 
With the recent changes to the Event Bus(https://github.com/UserOfficeProject/user-office-core/pull/1086), this functionality was no more working with the error thrown. It has been fixed by handling the error. In addition to that, the corresponding e2e tests for the functionality has also been created, so that it is caught during the CI/CD. In more addition to that, the type definition for the event argument has been optimized, so that during build time, the error could be caught improving developer experience
Fix Event Bus Decorator Issue
Attached the missing e2e test …
> fix: failure of automatic fap assignments during instrument picker selection fixed

- apps/backend/src/factory/DownloadService.ts
- apps/backend/src/middlewares/tracing/tracing.ts
This PR introduces trace context propagation for factory calls in our backend service.
The change is required to improve the observability of our application by tracing the factory service calls. This will help in identifying any issues, bottlenecks, or errors that may occur during the execution of these service calls and aid in debugging and optimization.
1. Added OpenTelemetry API for context propagation and tracing.
2. Refactored the fetch call to the factory service to be within a tracer span.
3. Added error handling within the tracer span to record exceptions and set the status of the span appropriately.
Through Grafana traces and service graph
https://github.com/UserOfficeProject/issue-tracker/issues/1433
https://github.com/UserOfficeProject/user-office-factory/pull/637
> feat: trace context propagation for factory calls

- .vscode/launch.json
This PR corrects the `webRoot` path in the launch configuration to fix ability for frontend debugging.
The path in the `webRoot` seems to be misconfigured, which results that when attaching debugger to the frontend no breakpoints are hit.
If the existing configuration works for you please let me know, so that fixing this for one environment does not break it for another.
- The `webRoot` path in the `launch.json` configuration file has been updated from `"${workspaceFolder}"` to `"${workspaceFolder}/apps/frontend"`, aligning it with the actual frontend application directory.
How to test:
1. Launch the backend and frontend services and make sure localhost:3000 renders properly.
2. Click the "Debug on <browser>"
> fix: correct webRoot path in launch configuration for frontend debugging

- apps/backend/src/auth/QuestionaryAuthorization.ts
This PR removes an unused import, SampleDataSource, from QuestionaryAuthorization.ts.
The SampleDataSource import was not being utilized, which led to unnecessary code clutter and potential confusion. Removing this unused import improves code readability and maintains a clean code environment.
- Removed the unused SampleDataSource import from QuestionaryAuthorization.ts.
- Removed the SampleDataSource injection from the QuestionaryAuthorization constructor.
These changes streamline the QuestionaryAuthorization file and adhere to best coding practices by eliminating unnecessary code.
> fix: remove unused SampleDataSource import

- apps/backend/src/datasources/postgres/ProposalDataSource.ts
Missing ? in the ILIKE query leads to error while searching. This happens when Instrument Scientists searches in the Proposal table. 
To fix the error in Instrument Scientist Proposal table, where searching is buggy.
Manually
Added ? alongside ILIKE in the raw query
> fix: ilike in the sql query leads to search error in the instrument scientist proposal page

- apps/frontend/src/components/call/AssignedInstrumentsTable.tsx
Closes https://github.com/UserOfficeProject/issue-tracker/issues/1172
This PR allows instrument availability time to be null in the AssignedInstrumentsTable component.
This change is required to handle cases where the instrument availability time is unknown or not provided as the call can be se up ahead of time.
- Added a condition in the validation logic of the AssignedInstrumentsTable component to allow `null` for the `availabilityTime` property.
The motivation behind this change comes from the need to handle real-life scenarios where sometimes the availability time of an instrument might not be known, hence allowing `null` values helps to maintain the integrity of the application.
> fix: instrument availability time can be null
