README.md
After the move to monorepo the Readme now needs to be updated
We want readme with relevant info
Readme
N/A
=> chore: Update README.md to contain updated information

apps/user-office-backend/Dockerfile
Small improvements to dockerfile
Set image to latest LTS
=> Dockerfile improvements

apps/user-office-frontend-e2e/cypress/integration/generic_templates.ts
=> try-no-context-before-each

apps/user-office-frontend-e2e/cypress/integration/samples.ts
Fix race condition where before each in context was run simultaneously with before each in the suite.
=> fix: Fix race condition for samples

apps/user-office-backend/package-lock.json, apps/user-office-backend/package.json, apps/user-office-frontend/package-lock.json, apps/user-office-frontend/package.json
When date fields do not meet validation requirements in sub templates, the sub template hangs
This will improve user experience 
Manual tested
https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/689
Validation of date fields in questions PR
https://github.com/UserOfficeProject/user-office-lib/pull/157
=> fix: Update date validation in questions

.github/workflows/build-push.yml
=> fix: update workflow from develop

.github/workflows/build-push.yml
This PR aims to make workflows more simple, by using two new custom actions
https://github.com/swapActions/get-branch-name 
https://github.com/swapActions/trigger-useroffice-deployment
This PR also updates old actions to address the warnings for deprecation
=> Updating workflows

.github/workflows/build-push.yml
This PR aims to fix the where generating SDK step was missing
=> fix: generating SDK

apps/user-office-frontend-e2e/.gitignore, apps/user-office-frontend-e2e/cypress/integration/SEP.ts, apps/user-office-frontend-e2e/cypress/integration/generalSeps.ts, apps/user-office-frontend-e2e/cypress/integration/proposals.ts, apps/user-office-frontend-e2e/cypress/support/utils.ts, apps/user-office-frontend-e2e/package-lock.json, apps/user-office-frontend-e2e/package.json, apps/user-office-frontend/src/components/SEP/Proposals/SEPProposalsAndAssignmentsTable.tsx, apps/user-office-frontend/src/components/SEP/SEPsTable.tsx, apps/user-office-frontend/src/components/proposal/ProposalTable.tsx, apps/user-office-frontend/src/components/proposal/ProposalTableOfficer.tsx
1. As a user I want to be able to copy IDs easily by clicking the helper "Copy to clipboard"  button.
2. E2e test for copy clipboard is covered
3. `cypress-real-events` package is installed and used to simulate real events
4. e2e test fail fix also included - ```Timed out retrying after 15000ms: Expected to find element: `[aria-label="Edit"]`, but never found it.``` error pops up sometimes.  Replaced `.parent()` method with `.closest()` to get the element more effectively.
e2e test 
* manual test
* e2e test
apps/user-office-frontend/src/components/proposal/ProposalTable.tsx
apps/user-office-frontend/src/components/proposal/ProposalTableOfficer.tsx
apps/user-office-frontend/src/components/SEP/Proposals/SEPProposalsAndAssignmentsTable.tsx …
=> apply copy to clipboard feature for copying Proposal id & SEP code

.github/workflows/build-push.yml
=> fix: fix pod recreation

.github/workflows/build-push.yml
=> Fix pod recreation

apps/user-office-backend/src/eventHandlers/messageBroker.ts
This PR adds instrument ID and shortcode to the Rabbit MQ message
Dependant systems require this information to be there
Manual tests
https://jira.esss.lu.se/browse/SWAP-3050
Message brokenr
NA
=> fix: add instrument to RabbitMQ message

.github/workflows/test-build.yml
=> Fix use right node version

.github/workflows/build-push.yml, .github/workflows/github-tag-and-release.yml, .github/workflows/lint.yml
This PR updates the remaining scripts used also for deployment so that the right node version is used. This makes sure that the merged code into development gets deployed on the test servers.
=> fix: fix deployment scripts

apps/user-office-backend/src/config/ess/configureESSEnvironment.ts, apps/user-office-backend/src/config/updateOIDCSettings.ts, apps/user-office-frontend-e2e/cypress/integration/appSettings.ts
=> fix: configure auth server when configuring environment

apps/user-office-backend/src/datasources/postgres/AdminDataSource.ts
A few things fell through the cracks when doing #200 since we needed it for the release. This just removes an infinite loop and changes a protected var to private.
=> fix: Clean up db patches initialised check

apps/user-office-backend/src/auth/OAuthAuthorization.ts, apps/user-office-backend/src/auth/StfcUserAuthorization.ts, apps/user-office-backend/src/auth/UserAuthorization.ts, apps/user-office-backend/src/auth/mockups/UserAuthorization.ts, apps/user-office-backend/src/datasources/stfc/UOWSSoapInterface.ts, apps/user-office-backend/src/mutations/UserMutations.ts
This fixes the error on logout on local dev.
Manual testing.
Part of UserOfficeProject/user-office-project-issue-tracker#829
=> fix: Fixes error on logout

.github/workflows/test-build.yml
Let it build to test the docker build operation but do not push and login to the registry
=> chore: Build but not push images from dependabot

apps/user-office-frontend-e2e/cypress/integration/proposals.ts
This is to fix stfc proposals tests that are long running and not able to finish.
This refactor and split internal call tests.
Closes : https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/853
Files changed : 
apps/user-office-frontend-e2e/cypress/integration/proposals.ts
=> Fix proposals stfc long running tests

apps/user-office-frontend/Dockerfile
=> Add python to docker build, needed for ARM build

README.md, docker-compose.yml
As more people are wanting to test the software we want to provide a easy way for people to get a local environment up and running. The easiest way to do this is to provide the smallest docker-compose file needed for running the user office core.
Make it easier for people to get a demo instance running
=> Added docker-compose file in root for easy testing of software

apps/user-office-frontend-e2e/cypress/e2e/pdfTemplates.cy.ts, apps/user-office-frontend/package-lock.json, apps/user-office-frontend/package.json, apps/user-office-frontend/src/components/template/PdfTemplateEditor.tsx
Introducing Code mirror editor for the PDF template editor
The present editor is basic text area and it is difficult to write HTML code on it. Hence introducing specialized editor. 
Both Manual and Cypress
=> Swap 3392 code editor

apps/user-office-backend/src/auth/StfcUserAuthorization.ts, apps/user-office-backend/src/datasources/stfc/UOWSSoapInterface.ts
Updates the UOWS WSDL from the latest generator. I also had to make some changes to the logout in the auth file as it turns out we had mistakenly made some direct changes to the interface previously.
The WSDL is taken from https://devapis.facilities.rl.ac.uk/ws/UserOfficeWebService?wsdl
New UOWS version
I tested the logout particularly and no errors. Also had a click around and created a proposal while adding a co-i.
Resolves [#903](https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/903)
=> Update UOWS WSDL

apps/user-office-backend/src/datasources/stfc/StfcUserDataSource.ts
Small fix to stop the STFC data source from requesting users it already has found in the cache.
=> Fix stfc get users from fetching some users twice

apps/user-office-backend/src/datasources/stfc/StfcProposalDataSource.ts
Closes UserOfficeProject/user-office-project-issue-tracker#911
Internal reviewer view shows internal reviews for logged in user by filtering proposals. See https://github.com/UserOfficeProject/user-office-core/pull/259/files#diff-e35ed70f27e57da4903cc38928e433c5d357af6150cfd29043567560d5f95521
Allows STFC users to see their internal reviews
Tested manually
=> #911 stfcproposaldatasource gets internal reviews

apps/user-office-frontend/src/components/template/PdfTemplateEditor.tsx, apps/user-office-frontend/src/components/template/documentation.tsx
Add Documentation helper to PDF editor
To improve user experience.
Manually
=> Documentation for the PDF Editor done.

apps/e2e/cypress/e2e/proposals.cy.ts
e2e test cases for Automatic assignment of Instrument on a Proposal
Earlier, a new question component for Instrument picker has been introduced with an intention to bring automatic assignment of Instrument to a Proposal, when the Question is answered. 
Cypress
=> test case of automatic assignment of isntrument to a proposal done.

apps/backend/src/mutations/CallMutations.spec.ts, apps/backend/src/resolvers/mutations/UpdateCallMutation.ts, apps/frontend/src/components/call/CallsTable.tsx
Fixing test case backend
A backend unit test case was failing, but the PR was merged. This is the followup PR for the fix. 
Unit test
Test case 
Change in request data structure for call instrument assignment.
=> fixing test case backend.

apps/backend/package-lock.json, apps/backend/src/datasources/postgres/CallDataSource.ts, apps/backend/src/mutations/CallMutations.spec.ts, apps/backend/src/resolvers/queries/CallsQuery.ts, apps/backend/src/resolvers/types/Template.ts, apps/frontend/src/components/template/PdfTemplatesPage.tsx, apps/frontend/src/components/template/PdfTemplatesTable.tsx, apps/frontend/src/components/template/ProposalTemplatesTable.tsx, apps/frontend/src/graphql/template/getPdfTemplates.graphql, apps/frontend/src/models/questionary/QuestionaryEditorModel.ts
Number of calls count added to pdf proposals table
show number of calls, that are using the pdf template
manually
=> Swap 3471 pdf template table shows 0 templates

.github/workflows/build-push.yml, .github/workflows/codeql-analysis.yml, .github/workflows/github-tag-and-release.yml, .github/workflows/lint.yml, .github/workflows/test-build.yml
GitHub workflows are using the latest versions of actions.
=> ci: Update workflows to use the latest version of actions

docker-compose.yml
The USER_OFFICE_FACTORY_ENDPOINT variable is updated with the correct value.
=> fix: Update docker-compose.yml to use the proper factory URL

apps/frontend/package.json
Vite was trying to open a browser in our docker container and crashing, so I've added a `--no-open` to stop this. 
Frontend crashes on start in stfc development env
Manually
=> Fix stfc dev env

apps/frontend/src/components/proposal/ProposalTable.tsx, apps/frontend/src/components/review/ProposalTableReviewer.tsx, apps/frontend/src/components/review/ReviewStatusFilter.tsx
This PR modifies the usage of the Material Table component in the application to enhance the user interface and fix minor issues in the reviewer table filters.
The change is required to improve the user interface by making it more intuitive and to fix minor issues in the reviewer table filters that might hinder the user's experience.
1. Replaced the wrapper function for columns with the dense Material Table in ProposalTable.tsx and ProposalTableReviewer.tsx files. This provides a more straightforward and efficient way to define columns for the Material Table.
2. Removed unused imports and styles in ProposalTableReviewer.tsx and ReviewStatusFilter.tsx files, reducing code clutter and improving code readability.
3. Adjusted the FormControl in ReviewStatusFilter.tsx to take full width for …
=> fix: use dense material table instead of the wrapper function for columns and fix minor UI issues in the reviewer table filters

.husky/pre-commit, package.json
Dependabot upped husky to v9 in #493 
The [migration guide](https://github.com/typicode/husky/releases/tag/v9.0.1) said it was backwards compatible, but a couple of changes should be made later. This PR contains those changes.
=> Update husky hooks following v9 update

apps/backend/package-lock.json, apps/backend/package.json, apps/backend/src/eventHandlers/MailService/SMTPMailService.ts
This hot fix smtp failure to sent emails because we now do not use certificates when sending emails. 
We are currently not able to send emails form the system because of changes on our email exchange.
Manual testing.
Files :apps/backend/src/eventHandlers/MailService/SMTPMailService.ts
Manual local testing.
=> This removes tls by default when smtp login not set

docker-compose.yml
Small typo made docker-compose file not work
=> Fix: Update docker-compose.yml

.github/pr-title-checker-config.json, .github/workflows/github-tag-and-release.yml, .github/workflows/pr-title-checker.yml, apps/e2e/cypress/e2e/settings.cy.ts
This PR introduces a title formatting check for all pull requests to maintain a consistent style across the project.
There was a need to enforce a consistent title formatting for all PRs to improve readability and maintainability. This change will ensure that all PR titles adhere to a predefined format, making them easier to understand and manage.
- A new PR title checker workflow has been added, which will run on every PR event such as opened, edited, synchronized, labeled, and unlabeled.
- A new configuration file, pr-title-checker-config.json, has been created to define the rules of the title formatting.
- Updated the version of the `github-tag-action` used in `github-tag-and-release.yml` from v6.1 to v6.2.
[https://jira.esss.lu.se/browse/SWAP-3868](https://jira.esss.lu.se/browse/SWAP-3 …
=> ci: add PR tittle formatting check

apps/backend/src/resolvers/types/Instrument.ts, apps/backend/src/statusActionEngine/statusActionUtils.ts, apps/e2e/cypress/e2e/instruments.cy.ts, apps/frontend/src/components/instrument/AssignedScientistsTable.tsx, apps/frontend/src/components/instrument/CreateUpdateInstrument.tsx, apps/frontend/src/components/review/AssignTechnicalReview.tsx, apps/frontend/src/graphql/instrument/instrument.fragment.graphql, apps/frontend/src/graphql/proposal/getProposal.graphql
As requested by our user officer the name beamline manager should be changed to instrument contact.
Be inline with convention at STFC and ESS
Manually
SWAP-3824
In frontend GUI, two files. 
NA
=> fix: change from beamline manager to instrument contact

apps/backend/package-lock.json, apps/backend/package.json, apps/backend/src/models/questionTypes/InstrumentPicker.ts, apps/e2e/cypress/e2e/proposals.cy.ts, apps/frontend/package-lock.json, apps/frontend/package.json
This PR addresses an issue with the instrument picker on the proposal page, improves its validation and covers it with an end-to-end test. 
The changes were necessary to fix a bug in the instrument picker, which was not functioning as expected. The upgrade in validation ensures that the data entered is accurate and the end-to-end test coverage ensures that any future changes do not break the functionality.
- Upgraded the version of @user-office-software/duo-validation from 5.0.1 to 5.0.2 in both backend and frontend.
- Fixed the bug in InstrumentPicker.ts by changing the default answer based on the "isMultipleSelect" flag.
- Added new end-to-end tests in proposals.cy.ts to cover the instrument picker functionality.
=> fix(instrument picker): fix instrument picker bug, upgrade its validation and cover it with e2e test

apps/backend/src/datasources/stfc/StfcProposalDataSource.ts
Fix https://github.com/UserOfficeProject/issue-tracker/issues/1058
Somehow this was working with the ptw object but the query is timing out on dev as it takes 4 mins to run the query in the db. This only takes 777ms changing not to us the pwt object as i should have done in the first place.
=> fix: query time out on stfc instrument sci query

apps/backend/db_patches/0154_MultipleFAPChair.sql, apps/backend/src/datasources/postgres/FapDataSource.ts, apps/backend/src/datasources/postgres/records.ts, apps/backend/src/datasources/stfc/StfcProposalDataSource.ts, apps/backend/src/factory/xlsx/stfc/StfcFapDataRow.ts, apps/backend/src/models/Fap.ts, apps/backend/src/resolvers/types/Fap.ts, apps/backend/src/statusActionEngine/statusActionUtils.ts, apps/e2e/cypress/e2e/generalFaps.cy.ts, apps/frontend/src/components/fap/Members/FapMembers.tsx, apps/frontend/src/components/fap/Proposals/FapProposalsAndAssignmentsTable.tsx, apps/frontend/src/graphql/fap/fragment.fap.graphql
Hotfix of some cherry-picked bug fixes and the ability to add multiple chairs
=> Hotfix 2024 04 23

apps/backend/src/datasources/stfc/StfcProposalDataSource.ts
Hotfix to fix filtering by instrument erroring
=> fix: instrument filtering sql query

apps/backend/src/factory/pdf/proposal.ts
This PR adds missing instrument picker information to the proposal PDF download functionality accessible via API token.
Closes: https://github.com/UserOfficeProject/issue-tracker/issues/1068
The change was required as the instrument picker information was not included in the proposal PDF download. This led to incomplete proposal information being downloaded, which could potentially lead to confusion or misinformation.
1. Introduced `InstrumentDataSource` to the `ProposalPDFData` object to fetch and include instrument details.
2. Replaced the synchronous `addTopicInformation` function with an asynchronous one to accommodate the fetching of instrument details, which is an asynchronous operation.
3. Updated how we fetch instruments for technical reviews to use the newly introduced …
=> fix: add missing instrument picker information to proposal pdf download by api token

.github/workflows/deploy-docs-develop.yml, .github/workflows/deploy-docs-latest.yml, documentation/README.md, documentation/docs/index.md, documentation/docs/technical/index.md, documentation/docs/user/index.md, documentation/docs/user_officer/index.md, documentation/mkdocs.yml
This PR introduces a new feature that adds User Office documentation to the project.
The addition of User Office documentation is aimed at providing comprehensive guidelines and instructions to users and user officers. This is essential for easing the use of the User Office, promoting understanding of its functionalities, and ensuring that users can solve common issues they may encounter while using it.
1. Implemented two new GitHub workflows for deploying documentation for the develop and release versions respectively. These workflows trigger on push events or when a new release is created.
2. Added markdown files for the User Office documentation. These files provide guidelines on how to update the documentation, test it locally, and information on its automatic deployment.
3. …
=> feat: add User Office documentation

apps/backend/src/datasources/stfc/StfcProposalDataSource.ts
Closes: https://github.com/UserOfficeProject/issue-tracker/issues/1110
Proposal are not showing up for proposals with no instrument assigned to them, looking into it the logic of the instrument scientist proposals was wrong for stfc.
=> fix: stfc inst sci proposal view

documentation/mkdocs.yml
Added new plugins - Admonition(Collapsible), Annotation, Image, Tooltip for the documentation framework
To enhance the documentation by adding valuable plugins. 
Manually
Add the plugins in the mkdocs.yml file.
=> feat: added new plugins to the documentation

documentation/docs/user-guide/user-officer/creating_call.md, documentation/docs/user-guide/user-officer/editing_call.md, documentation/docs/user-guide/user-officer/fap.md, documentation/docs/user-guide/user-officer/proposal_workflow.md, documentation/docs/user-guide/user-officer/templates/pdf_template.md, documentation/docs/user-guide/user-officer/templates/proposalESI_template.md, documentation/docs/user-guide/user-officer/templates/templates.md, documentation/docs/user-guide/user-officer/videos.md, documentation/mkdocs.yml
* Updated the documentation for the templates sections
* Updated information for FAPs and proposal workflows
* Created structure for future video tutorial pages
* Fixed multiple broken links
=> docs: improved user guide templates

documentation/docs/developer-guide/configuration.md, documentation/mkdocs.yml
Created page for configuration, how to set up .env and information about different variables.
=> docs: create page for configuration

documentation/docs/developer-guide/email.md, documentation/docs/developer-guide/kubernetes.md, documentation/docs/developer-guide/rabbitmq.md, documentation/docs/faq.md, documentation/docs/glossary.md, documentation/docs/user-guide/user-officer/calls.md, documentation/docs/user-guide/user-officer/fap.md, documentation/docs/user-guide/user-officer/main/creating_call.md, documentation/docs/user-guide/user-officer/main/templates.md, documentation/docs/user-guide/user-officer/main/user-officer.md, documentation/docs/user-guide/user-officer/page.md, documentation/docs/user-guide/user-officer/questions.md, documentation/docs/user-guide/user-officer/settings/proposal_workflow.md, documentation/docs/user-guide/user-officer/templates/feedback_template.md, documentation/docs/user-guide/user-officer/templates/proposalESI_template.md, documentation/docs/user-guide/user-officer/templates/proposal_template.md, documentation/docs/user-guide/user-officer/templates/shipment_template.md, documentation/mkdocs.yml
fixed links, added page for setting up email service
=> docs: fix links, add page for setting up email service

apps/frontend/src/components/common/DownloadableFileList.tsx, apps/frontend/src/components/common/FileLink.tsx, apps/frontend/src/components/common/FileUploadComponent.tsx
Closes: https://github.com/UserOfficeProject/issue-tracker/issues/1157
Added some auth to the download links by making a new link component. Let me know what you think of this solution
=> fix: download links not working

apps/frontend/src/utils/Time.ts
Fixes an awkward typo. Hoping to include this in our hotfix that goes out today
=> fix: month typo

apps/backend/src/datasources/postgres/UserDataSource.ts
This PR fixes an issue where dummy users were being created even for existing users.
This change is required to prevent the creation of unnecessary dummy user records in the database, which could lead to confusion and data inconsistency.
- Modified the insert method in UserDataSource.ts to only create dummy users for users that do not exist in the database.
=> fix: dont add dummy users for existing users

apps/backend/src/datasources/postgres/FileDataSource.ts, apps/backend/src/factory/StfcDownloadService.ts
Hotfix for https://github.com/UserOfficeProject/issue-tracker/issues/1163 now that it's been tested on dev via https://github.com/UserOfficeProject/user-office-core/pull/779
Also added a commit a87300c0a35c0bd99d418f2dc8228220f35394b4 for some better logging.
=> fix: serving STFC PDFs from Postgres

apps/backend/src/datasources/postgres/GenericTemplateDataSource.ts
This PR fixes the incorrect canCopy logic in the generic template. It previously checked the `templates_has_questions` table where the generic template ID existed and got the first row. But the table contains a row for each template the generic template is used on, so we need to get the row that corresponds to the current proposal template, to see if the question configuration allows copying. Without this it leads to arbitrary behaviour where it can pick up another template's configuration.
This isn't necessarily the best way of doing it, I think ideally this check would move to mutation level. But it's needed for a fix very soon.
The change is required to ensure the canCopy logic correctly checks if a generic template can be copied based on the proposal template's settings, improving the …
=> fix: generic template incorrect canCopy logic

apps/backend/src/datasources/postgres/FapDataSource.ts, apps/backend/src/datasources/postgres/ReviewDataSource.ts, apps/backend/src/factory/DownloadService.ts, apps/backend/src/factory/xlsx/proposal.ts, apps/backend/src/middlewares/factory/xlsx.ts, apps/e2e/cypress/e2e/xpress.cy.ts, apps/frontend/src/components/fap/Proposals/FapProposalsAndAssignmentsTable.tsx, apps/frontend/src/components/review/ProposalTableReviewer.tsx, apps/frontend/src/components/xpress/XpressProposalTable.tsx, apps/frontend/src/context/DownloadContextProvider.tsx, apps/frontend/src/graphql/proposal/getTechniqueScientistProposalsBasic.graphql, apps/frontend/src/hooks/proposal/useDownloadXLSXProposal.ts
=> Release 8 11 2024

apps/frontend/src/components/review/ReviewSummary.tsx
Review submission notification message needs to be updated
Message about submission is wrong.
Manual + e2e
Update notification message: remove reference about email sending. 
Frontend change. 
N/A
- [ x] I have added tests to cover my changes.
- [ x] All relevant doc has been updated
=> fix: update notification message about review submission

apps/backend/src/datasources/CallDataSource.ts, apps/backend/src/datasources/mockups/CallDataSource.ts, apps/backend/src/datasources/postgres/CallDataSource.ts, apps/backend/src/datasources/postgres/StatusActionsLogsDataSource.ts, apps/backend/src/factory/pdf/proposal.ts, apps/backend/src/queries/CallQueries.ts, apps/backend/src/resolvers/queries/CallQuery.ts, apps/backend/src/resolvers/types/StatusActionsLog.ts, apps/frontend/src/components/common/FileLink.tsx, apps/frontend/src/components/questionary/questionaryComponents/InstrumentPicker/InstrumentPickerAnswerRenderer.tsx, apps/frontend/src/components/statusActionsLogs/StatusActionsLogsTable.tsx, apps/frontend/src/context/DownloadContextProvider.tsx, apps/frontend/src/graphql/call/getCallAllocatedTimeUnit.graphql, apps/frontend/src/graphql/call/getCallByQuestionId.graphql, apps/frontend/src/graphql/statusActionsLogs/fragment.statusActionsLog.graphql, apps/frontend/src/graphql/statusActionsLogs/getStatusActionsLogs.graphql, apps/frontend/src/hooks/call/useQuestionCallData.ts
=> Release 25 11 24

copyIfNotExist.js
Refactored the `copyIfNotExist.js` script to improve readability and maintainability by removing redundant lines and simplifying logic.
=> chore: clean up copyIfNotExists.js util

apps/backend/src/datasources/stfc/StfcProposalDataSource.ts, apps/e2e/cypress/e2e/xpress.cy.ts, apps/frontend/src/components/xpress/XpressProposalTable.tsx
This PR introduces minor fixes and improvements to the Xpress application, improving the UI and data handling.
The changes in this PR were necessary to enhance the usability of the application and to ensure correct data handling and representation. This includes improved sorting and presentation of data in the Xpress proposal table, as well as better handling of calls in the backend.
1. In the backend, a new dependency `CallDataSource` is introduced in `StfcProposalDataSource.ts` to handle calls with 'QUICK_REVIEW' status. This ensures that these calls are correctly handled and excluded from certain queries.
2. In the frontend, several changes have been made to `XpressProposalTable.tsx` to improve data presentation. This includes:
- Introducing a new `cellStyleSpecs` for text overflow …
=> fix: xpress minor issue fixes

apps/frontend/src/components/questionary/questionaryComponents/InstrumentPicker/QuestionaryComponentInstrumentPicker.tsx
Closes https://github.com/UserOfficeProject/issue-tracker/issues/1296
Instruments were showing in a random order that was causing confusion to users.
=> fix: sort instruments in alphabetical order

apps/backend/.dockerignore
This PR updates the Docker ignore file to include the 'openapi.yaml' file.
The change is necessary to ensure the 'openapi.yaml' file is not ignored by Docker. This file is essential for the proper functioning of our backend services and its absence could potentially lead to application errors or malfunctions.
- The '.dockerignore' file has been updated to include the 'openapi.yaml' file, ensuring it is not overlooked during the Docker image creation process.
- An extra newline has been added at the end of the file to adhere to standard file formatting conventions.
=> chore: update docker ignore

apps/e2e/cypress/e2e/FAPs.cy.ts
Our e2e tests have been consistently failing since the weekend on the same test with the same error.
```
1) Fap reviews tests
[0]        User officer role
[0]          Officer should be able to assign ranks to reviewers:
[0]      AssertionError: Timed out retrying after 30000ms: Expected to find content: '1' within the element: <tr.MuiTableRow-root.css-1s4nfbj-MuiTableRow-root> but never did.
[0]       at Context.eval (webpack://user-office-core-e2e/./cypress/e2e/FAPs.cy.ts:428:0)
```
Still not sure why they started failing, since no PR seems to have touched this file for a couple weeks and we only just started seeing this error, and if it was a PR that broke this then surely the tests would have had to pass for it to be able to merge...
Nevertheless, this seems to get the test running …
=> test: fix broken e2e test

apps/backend/package-lock.json, apps/frontend/public/locales/override/translation.json, apps/frontend/src/components/instrument/AssignedScientistsTable.tsx, apps/frontend/src/components/instrument/CreateUpdateInstrument.tsx
Closes https://github.com/UserOfficeProject/issue-tracker/issues/1332
Renamed Instrument Contact to Area Contact according to CLF requirements.
Linked to: https://git.devs.facilities.rl.ac.uk/isisbusapps/BisAppSettings/pulls/573
=> refactor: rename instrument contact to area contact for clf

apps/backend/src/models/questionTypes/TechniquePicker.ts
This PR addresses the issue of unsorted techniques in the technique picker. 
The change is required to improve the user experience by providing a sorted list of techniques, making it easier for users to find the desired technique.
- Techniques in the technique picker are now sorted alphabetically. The sorting logic is applied right after mapping the techniques to `TechniqueOptionClass` instances, ensuring a correctly sorted list is returned to the user.
https://github.com/UserOfficeProject/issue-tracker/issues/1339
=> fix: techniques sorting in technique picker

apps/backend/src/auth/StfcUserAuthorization.ts
Closes UserOfficeProject/issue-tracker#1359
The PR removes hardcoded references to the STFC instrument "ARTEMIS" as we are going to deploy reviews and now need to use the instrument as instrument, not a kind of facility. 
=> chore: remove stfc hardcoded instrument artemis

apps/frontend/src/components/fap/MeetingComponents/ProposalViewModal/ExternalReviews.tsx
Closes UserOfficeProject/issue-tracker#1361
old
new
=> fix: fix proportions of external reviews table

apps/backend/package-lock.json, apps/backend/package.json
The PR removes the newman dependency from the backend package.json file.
Newman dependency was not used within the backend codebase. Removing unused dependencies helps keep the codebase clean, manageable, and reduces potential security risks. 
- Removed newman dependency from package-lock.json.
- Removed associated dependencies of newman from package-lock.json.
=> chore: remove newman dependency from backend package.json

apps/frontend/src/components/pages/OverviewPage.tsx, apps/frontend/src/components/proposalBooking/UserUpcomingExperimentsTable.tsx
The PR refactors the code to add margins and simplify the component structure of the OverviewPage and UserUpcomingExperimentsTable.
The changes are required to improve the visual appearance and readability of the code. It makes the component structure more straightforward and easier to understand, thus enhancing maintainability.
1. Renamed `PaperContainer` to `Paper` and added margin in `OverviewPage.tsx`.
2. Simplified the rendering of `roleBasedOverView` by removing unnecessary wrapper components in `OverviewPage.tsx`.
3. Removed the usage of `Grid` and `StyledPaper` from `UserUpcomingExperimentsTable.tsx`, keeping it consistent with other parts of code
[https://jira.esss.lu.se/browse/SWAP-4560](https://jira.esss.lu.se/browse/SWAP-4560)
=> fix: add margin and simplify component structure

apps/frontend/src/components/menu/MenuItems.tsx
Closes https://github.com/UserOfficeProject/issue-tracker/issues/1366
This PR fix hoover on experimental area icon. 
Fix hoover on experimental area icon.
Manually tested the changes in local.
apps/frontend/src/components/menu/MenuItems.tsx
=> fix: hoover on experimental area icon#1366

apps/frontend/src/components/feedback/CreateFeedback.tsx, apps/frontend/src/components/shipments/CreateShipment.tsx, apps/frontend/src/components/template/FeedbackTemplatesPage.tsx, apps/frontend/src/components/template/ShipmentTemplatesPage.tsx, apps/frontend/src/components/template/TemplatesTable.tsx, apps/frontend/src/components/template/VisitTemplatesPage.tsx, apps/frontend/src/components/template/withMarkTemplateAsActiveAction.tsx, apps/frontend/src/components/visit/CreateUpdateVisitRegistration.tsx, apps/frontend/src/components/visit/CreateVisitRegistration.tsx, apps/frontend/src/hooks/feedback/useBlankFeedback.ts, apps/frontend/src/hooks/shipment/useBlankShipment.ts, apps/frontend/src/hooks/visit/useBlankVisitRegistration.ts
This PR addresses with user experience when active template is not set, as well as refactors how blank Visit and Feedback objects are contructed.  
Currently if active template is not set user will see infinite loading screen for feedback and visits which is a bad user experience
This fix shows a proper error message for the user.
Additionally to raise awareness, the error message is displayed for the user officer when visiting the templates table view and no templates has been defined
Lastly this PR makes sure that if user sees this error, the addClientLog is called and the issue is reported.
This PR makes sure that Feedback and Visits is now consistent with Shipment implmenentation.
CreateShipment uses createBlankShipment hook to create new, empty shipment object.
Similarely now the …
=> fix: silent failure if active template is set
